### ISSUE TITLE
Deprecate installation of VPC resource controller

### ISSUE THREAD

**Issue by cPu1** [eksctl-io/eksctl#2401]
In a future release, EKS will start running the VPC resource controller components on the control plane. Today, eksctl has a command to install the VPC resource controller on worker nodes, and requires having at least one Linux worker node in the cluster. This command will no longer be required for EKS version 1.16 and above, but should still be supported for previous versions and eventually deprecated when support for EKS 1.15 is removed. Existing 1.16 clusters will be automatically upgraded by EKS to a newer platform version that is yet to be determined. 

As part of this change, eksctl should warn if `--install-vpc-controller` is specified in `eksctl create cluster` for EKS version 1.16 and above. Additionally, when a command (like `create nodegroup`) is run and eksctl finds that the VPC resource controller is installed, it should:
1. Instruct the user to delete it, e.g., via kubectl. The exact resources to delete can be specified in the instructions.
2. ~Instruct the user to delete any Linux nodegroups that were dedicated for running the VPC resource controller.~

See https://github.com/aws/containers-roadmap/issues/1280#issuecomment-780734054

**Comment by michaelbeaumont** [comment]
Check platform versions for 1.16 platform 3 and 1.17 platform 2

**Comment by andrea-maruccia-leaseplan** [comment]
@michaelbeaumont is this the case already? I cannot see any reference in the AWS documentation that the VPC resource controller isn't needed anymore

**Comment by michaelbeaumont** [comment]
Nope, nothing has changed here yet.

**Comment by cPu1** [comment]
This is blocked on AWS patching all existing EKS clusters to enable support for Windows IPAM on the control plane.

**Comment by Himangini** [comment]
Closing. See here for info https://github.com/aws/containers-roadmap/issues/1280#issuecomment-965678368
