### ISSUE TITLE
Deprecated apiVersion used for MutatingWebhookConfiguration and CertificateSigningRequest

### ISSUE THREAD

**Issue by nluckenbill** [eksctl-io/eksctl#3873]
Hello, when creating a new admission controller, eksctl prints out the following warnings:
```
warnings.go:67] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
```

```
warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```

This can be reproduced following the instructions here\:
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

**VERSIONS**

```
Admin:~/environment $ eksctl version
0.53.0
Admin:~/environment $ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cPu1** [comment]
Thanks for the heads-up, we'll work on this soon.

**Comment by Callisto13** [comment]
@cPu1 are you actively writing this at the moment? If not can you un-assign and throw it back into the pool?

**Comment by awsitcloudpro** [comment]
In addition to switching to the stable API versions, it will be best to stay away from the Legacy K8s signer, and instead use `cert-manager` or similar tool to issue the certificate for the admission webhook.

**Comment by Callisto13** [comment]
@cPu1 do you know if we are still blocked upstream on this?

**Comment by cPu1** [comment]
> @cPu1 do you know if we are still blocked upstream on this?

We're blocked upstream on `CertificateSigningRequest`, but not on `MutatingWebhookConfiguration`. We should be able to migrate to `admissionregistration.k8s.io/v1`.

**Comment by cPu1** [comment]
We have a merged [PR](https://github.com/weaveworks/eksctl/pull/4338) that we had to revert temporarily, that will remove the need for installing the VPC controller in order to run Windows workloads, making this issue obsolete. We'll close this issue when we re-merge that PR back.

**Comment by cPu1** [comment]
Not stale, this is blocked on AWS.

**Comment by cPu1** [comment]
This is obsoleted by https://github.com/eksctl-io/eksctl/pull/4338.
