### ISSUE TITLE
[Feature] Support AWS ISO (US) partition's regions

### ISSUE THREAD

**Issue by mblum14** [eksctl-io/eksctl#5656]
### What feature/behavior/change do you want?

Support for us-iso-east-1 and us-iso-west-1 regions

### Why do you want this feature?

unable to use eksctl for those regions

**Comment by Himangini** [comment]
@mikestef9 @josefaworks FYI

**Comment by cPu1** [comment]
Support for `us-iso-east-1` is out in https://github.com/weaveworks/eksctl/releases/tag/v0.148.0.

**Comment by cPu1** [comment]
Support for `us-iso-west-1` has also been merged: https://github.com/eksctl-io/eksctl/pull/6997
