### ISSUE TITLE
[Task] Remove support for EKS version 1.22

### ISSUE THREAD

**Issue by Himangini** [eksctl-io/eksctl#6202]
### Description
As per the calendar for [Amazon EKS end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) June 4, 2023 is the end of support for Kubernetes version 1.22 

We need to remove support for 1.22 and modify any relevant docs wherever possible.
Reference PR - see [here](https://github.com/weaveworks/eksctl/pull/5073)

Note: This task needs to be picked up when the dates are confirmed.

**Comment by watany-dev** [comment]
I would like to contribute to this if you would like. Will you be able to make it in time?

**Comment by Himangini** [comment]
@watany-dev 

> I would like to contribute to this if you would like. Will you be able to make it in time?

@watany-dev are you still looking to contribute to this? Pls, open a PR asap 👍🏻

**Comment by watany-dev** [comment]
@Himangini 
Thanks, I just created a build environment for this opportunity:)
