### ISSUE TITLE
[Feature] separate NAT gateways in each AZ

### ISSUE THREAD

**Issue by matti** [eksctl-io/eksctl#6394]
aws sent this email on eksctl created clusters:

> Hello,
> We have observed that your Amazon VPC resources are using a shared NAT Gateway across multiple Availability Zones (AZ). To ensure high availability and minimize inter-AZ data transfer costs, we recommend utilizing separate NAT Gateways in each AZ and routing traffic locally within the same AZ.
Each NAT Gateway operates within a designated AZ and is built with redundancy in that zone only. As a result, if the NAT Gateway or AZ experiences failure, resources utilizing that NAT Gateway in other AZ(s) also get impacted. Additionally, routing traffic from one AZ to a NAT Gateway in a different AZ incurs additional inter-AZ data transfer charges. We recommend choosing a maintenance window for architecture changes in your Amazon VPC.

**Comment by ashutosrath** [comment]
We are also facing the same issue, getting many emails from AWS with similar content. 
I lost my ClusterCofig file, which I have used as part of EKSCluster creation. I did not find in any of the config maps.. Is it stored somewhere so I can change `--vpc-nat-mode` to Disabled as I don't need a NAT gateway? It seems eksctl has created the natGateway by default with (Single) as per the below documentation 

Refer https://eksctl.io/usage/vpc-configuration/#nat-gateway

**Comment by matti** [comment]
https://twitter.com/kylerippey/status/1633145726166528000?s=46&t=m4qWsItVC8dBPZYJZumEFw

**Comment by tanvp112** [comment]
Single or HA NAT gateway does not affect how EKS works, i.e. private cluster doesn't even need a IGW. NAT gateway is quite expensive, the hosting cost in each AZ can be more expensive than the cross AZ data charge for applications only need the access occasionally.

**Comment by jameslaneovermind** [comment]
From what I've seen a recommended solution is that you instead use a NAT gateway in each availability zone, meaning that a failure in one AZ won’t affect others. It also means that you won’t be paying for cross-AZ traffic that isn’t required (~$0.02 per GB). However you will be paying for 2x new NAT Gateways (~$0.05/hour)

Given this complexity, you really need to understand your workloads to determine what is the best/cheapest/easiest solution for you. Overmind is able to help you with this.

[https://overmind.tech/blog/nat-gateway-aws](https://overmind.tech/blog/nat-gateway-aws)

**Comment by matti** [comment]
> What's the thinking for the default being to create a NAT Gateway (Single), rather than defaulting to Disable?

atleast ipv6 clusters can't disable/modify NAT Gateway setting. Just tried to "Disable" it and got:

> Error: setting NAT is not supported with IPv6

**Comment by matti** [comment]
ipv6 clusters with unnecessary nat gateway cost more for no reason

**Comment by matti** [comment]
still an issue and ipv6 cnt remove nat gw

**Comment by matti** [comment]
still an issue and ipv6 cant remove nat gw

**Comment by Himangini** [comment]
@matti Please open a support ticket with AWS directly. We don't have any control over the emails you receive from AWS. 

Note for community members: Please don't share the contents of your email correspondence with AWS here. If you do receive emails from AWS please respond to them via AWS preferred communication channels [**DO NOT Open issues here**].

**Comment by matti** [comment]
this https://github.com/eksctl-io/eksctl/issues/6394#issuecomment-1470438405
