### ISSUE TITLE
[Feature] Update addon to Default/recommended version

### ISSUE THREAD

**Issue by MartinEmrich** [eksctl-io/eksctl#6403]
### What feature/behavior/change do you want?

I would like to update all addons to te current default (i.e. recommended by AWS) version.
Currently, I can only 

- specify no version at all. Then, nothing happens (see also https://github.com/weaveworks/eksctl/issues/5565)
- explicitly specify a version. Having to look up the current default version on AWS, I can also click on Update there
- specify `latest`, indeed giving me the newest version AWS has in stock, which might not be the default version for the EKS version I am running.

Please also add a `default` version value doing that.

### Why do you want this feature?

Then eksctl would do the above, installing all recommended addon versions in one go.

Thanks!

**Comment by Himangini** [comment]
@MartinEmrich 
- During the creation of addon if you do not specify a version then eksctl will create the addon with the **`default`** EKS version. 
- If you are upgrading an existing addon and do not specify a specific version or `latest` then eksctl will preserve the existing version! 
- If you wish to upgrade your addon which is not currently on the `default` version then you can simply specify the version in the config file or command line. You can read more [here](https://eksctl.io/usage/addons/#setting-the-addons-version) 
- You can also discover what versions of your addon are available by running the following command before attempting to upgrade. 
``` eksctl utils describe-addon-versions --cluster <cluster-name> --name <addon-name>```

**Comment by MartinEmrich** [comment]
@Himangini yes, that seems to summarize the current state of things.

There seems to be no automatic "update to default version" option.

**Comment by MartinEmrich** [comment]
Could someone please disable that annoying github-actions bot? If the feature request is reasonable (I think it is), it's IMHO annoying.

**Comment by MartinEmrich** [comment]
/remove-label: stale

https://drewdevault.com/2021/10/26/stalebot.html
