### ISSUE TITLE
[Help] command arguments separated with `\ ` are misinterpreted

### ISSUE THREAD

**Issue by Bhavyasri05** [eksctl-io/eksctl#6762]
eksctl create iamserviceaccount \ --name ebs-csi-controller-sa \ --namespace kube-system \ --cluster eks2 \ --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \ --approve \ --role-only \ --role-name AmazonEKS_EBS_CSI_DriverRole \ --region us-east-1
2023-07-05 18:26:34 [✖]  only one argument is allowed to be used as a name

**Comment by yuxiang-zhang** [comment]
`\ ` might be adding a white space to the list of arguments, which causes the `--name ebs-csi-controller-sa` arguments to be misinterpreted. To work around the issue, could you please try dropping the `\`s or actually put the arguments on separate lines?
