### ISSUE TITLE
Cleanup Flux Integration

### ISSUE THREAD

**Issue by TiberiuGC** [eksctl-io/eksctl#6770]
As a result of [this spike](https://github.com/weaveworks/eksctl-private/issues/1052), the following action items were decided upon for cleaning up our Flux integration:

- to run the gitops integration test locally, against a non-org GitHub account, we need to add the `personal: true` flag. The purpose of this action item is to modify the test so that this flag can be configured from command line.
- cleanup userdocs - i.e. remove integration being experimental warning, remove reference to the old Flux API, tidy up references to Flux web page (there are 5 references, with duplicates, within just a few paragraphs)
- upgrade Flux minimum supported version which is currently over 3 years old (i.e. `0.13.3`) - e.g. Terraform controller supports `0.32` as min version, we could use that as-well.

**Comment by Himangini** [comment]
Looks like Flux `2.0.0` has some impact on our tests after all https://github.com/eksctl-io/eksctl-ci/actions/runs/5486414010/jobs/9996916285#step:19:97 
Needs to be looked into as part of this.

**Comment by TiberiuGC** [comment]
Another point: check whether it is possible to set the Flux version we use in our workflows, instead of always getting the latest (which may be an RC / unstable version).
