### ISSUE TITLE
[Help] Change default storage class of a node group - International Local Zones support

### ISSUE THREAD

**Issue by cneira84** [eksctl-io/eksctl#6775]
I'm using the definition of `localZones: ["us-east-1-bue-1a"]` in the cluster yaml, but I'm not able to find the proper parameter to change the storage class only for a nodegroup in the LZ. This is a problem for International Local Zones, since we don't have gp3 available. Any way to fix that? As a workaround, I'm changing that in the Launch Template after launch, but is not a friendly solution.

Thanks!

**Comment by TiberiuGC** [comment]
Hi @cneira84 . Does the example below help? Are you referring to setting `volumeType` to a different that default value, or is your use case somewhat different and I'm missing the nuance?

https://github.com/weaveworks/eksctl/blob/55d3e7fba119c291ef0d72dc425470374c03e6cd/examples/05-advanced-nodegroups.yaml#L10-L25

**Comment by cneira84** [comment]
Yes! Excellent. That should work. I'll try it and if I have any troubles
I'll be back.

**Comment by Himangini** [comment]
@cneira84 can this be closed?

**Comment by cneira84** [comment]
Yes, it's done.
