### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by nkamlesh** [eksctl-io/eksctl#6790]
for install eksctl on linux or anyother OS the github link is 
https://github.com/**eksctl-io**/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz
the copies of installation is available at 
"https://github.com/**weaveworks**/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"

so if you go to url: 
https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_windows_amd64.zip, you will find a message as  "**not found**", 
request you to **correct readme** file

**Comment by nkamlesh** [comment]
while installing eksctl from readme file on below: 
https://github.com/weaveworks/eksctl/blob/main/README.md#installation
was able to solve it by referring workshop of eks shared below:
https://catalog.us-east-1.prod.workshops.aws/workshops/165b0729-2791-4452-8920-53b734419050/en-US/1-create-workspace-environment/onown/setup-tools

**Comment by yuxiang-zhang** [comment]
Hi, you most likely tried our download URL before we actually did the repository transfer #6767, which happened today. 

> so if you go to url:
https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_windows_amd64.zip, you will find a message as "not found",
request you to correct readme file

This works only after the transfer, and should work from now on. Sorry for the inconvenience caused!
