### ISSUE TITLE
[Bug] cluster-dns-ip not supported for bottlerocket settings

### ISSUE THREAD

**Issue by kramuenke-catch** [eksctl-io/eksctl#6834]
Hi all,

we are trying to use `cluster-dns-ip` setting for a bottlerocket nodegroup. When using

```
  bottlerocket:
    settings:
      kubernetes:
        cluster-dns-ip: ["169.254.20.10","172.20.0.10"]
```

we get the following error:

```
Error:
 could not create cluster provider from options: invalid Bottlerocket 
setting: use nodeGroups[0].clusterDNS instead 
(path=nodeGroups[0].kubernetes.cluster-dns-ip)
```

Since we aim to use both node-local-dns ip and cluster ip we can not use `nodeGroups[0].clusterDNS` as an alternative.

**Comment by kramuenke-catch** [comment]
e.g. is it possible to remove the [overlap error](https://github.com/eksctl-io/eksctl/blob/55b2100c135c743e8d79852d03f599aa14717154/pkg/apis/eksctl.io/v1alpha5/validation.go#L1516) since `cluster-dns-ip` [supports](https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md#settings) a single IP and a list of IPs

**Comment by cPu1** [comment]
@kramuenke-catch this is a valid issue. Since `kubernetes.cluster-dns-ip` allows specifying a set of nameserver IPs, and `nodeGroup.clusterDNS` does not, eksctl should allow setting `kubernetes.cluster-dns-ip` if `clusterDNS` is not specified. We'll work on a fix soon.
