### ISSUE TITLE
[Bug] v0.149.0/0.150.0 prints 0.149.0-dev/0.150.0-dev as version

### ISSUE THREAD

**Issue by EHJ-52n** [eksctl-io/eksctl#6835]
### What were you trying to accomplish?

My eksctl update script compares the latest available release version with the version of the currently installed one and installs a new version if the versions are not the same.

### What happened?

The current latest available version when asking GitHub API is `0.149.0`.
When asking my currently installed eksctl binary which version it is, it reports to be `0.149.0-dev`.
As `0.149.0 != 0.149.0-dev` the "newer" release is installed everytime my update script is run.

### How to reproduce it?

```
~ curl --silent "https://api.github.com/repos/eksctl-io/eksctl/releases/latest" \
        | jq -r .tag_name \
        | sed 's/v\(.*\)/\1/' ; \
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/download/v0.149.0/eksctl_$(uname -s)_amd64.tar.gz" \
        | tar xz ; \
        chmod +x ./eksctl ; \
        ./eksctl version ; \
        rm eksctl
0.149.0
0.149.0-dev
```

**Logs**

**Anything else we need to know?**

I am posting this for documentation and hope that the next release will have the postfix `-dev` removed.

**Versions**

```
~ eksctl info                                                
eksctl version: 0.149.0-dev
kubectl version: v1.24.15
OS: linux
```

**Comment by jouve** [comment]
up, it happened again with v0.150.0-dev

**Comment by a-hilaly** [comment]
I'm expecting this to be coming from https://github.com/eksctl-io/eksctl/blob/main/.goreleaser.yml#L17 - maybe we are missing some env configuration in L13? /cc @cPu1

**Comment by cPu1** [comment]
> I'm expecting this to be coming from https://github.com/eksctl-io/eksctl/blob/main/.goreleaser.yml#L17 - maybe we are missing some env configuration in L13? /cc @cPu1

The env config is correct, the package name, however, is incorrect in `ldflags`. 

I have opened a [PR](https://github.com/eksctl-io/eksctl/pull/6841) with a fix, we'll aim to get it out in the next release.
