### ISSUE TITLE
Error: managedNodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (managedNodeGroups[0].ami)[Help] 

### ISSUE THREAD

**Issue by yossisp1972** [eksctl-io/eksctl#6837]
Hi,

I am getting this error

Error: managedNodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (managedNodeGroups[0].ami)

when trying to create a cluster using a custom linux AMI with --node-ami flag.
I did some reading and saw the changes you did with overrideBootstrapCommand but its not clear what needs to be done.

And what about windows AMI? I saw in a thread this is not needed in a windows AMI.

Please clarify.

**Comment by cPu1** [comment]
As the error message indicates, you need to provider an overrideBootstrapCommand when specifying a custom AMI. More details in [Custom AMI support](https://eksctl.io/usage/custom-ami-support).

**Comment by cPu1** [comment]
As the error message indicates, you need to provide an `overrideBootstrapCommand` when specifying a custom AMI. More details in [Custom AMI support](https://eksctl.io/usage/custom-ami-support).

**Comment by yossisp1972** [comment]
So what is this bootstrap.sh file? is this a script that runs at bootstrap
like user-data? Whats in it?

**Comment by yuxiang-zhang** [comment]
> So what is this bootstrap.sh file? is this a script that runs at bootstrap like user-data? Whats in it?

Hey, please refer to this comment: https://github.com/eksctl-io/eksctl/issues/6058#issuecomment-1352389881
and this comment: https://github.com/eksctl-io/eksctl/issues/6058#issuecomment-1403236938

Feel free to follow up with other questions ✋

**Comment by yossisp1972** [comment]
So this is still failing.
This is the error i am getting 
Error: timed out waiting for at least 2 nodes to join the cluster and become ready in "Synopsys": context deadline exceeded

 This is the YAML file i am using

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: synopsys-coverity-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0aa9bb5693a7c0cf6 }
      us-east-1b: { id: subnet-015329d3207246c28 }

nodeGroups:
  - name: Synopsys
    ami: ami-07aa3317551c8fd9e
    instanceType: t3.xlarge
    desiredCapacity: 2
    amiFamily: Ubuntu1804
    privateNetworking: true
    volumeSize: 120
    minSize: 2
    maxSize: 3
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh Synopsys_Coverity --kubelet-extra-args "--node-labels=$${NODE_LABELS}"
  - name: Coverity
    ami: ami-088c436a8500a51ab
    amiFamily: WindowsServer2019FullContainer
    volumeSize: 120
    privateNetworking: true
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.xlarge
    # overrideBootstrapCommand: |
    #   #!/bin/bash
    #   /etc/eks/bootstrap.sh Synopsys_Coverity

**Comment by yossisp1972** [comment]
So this is the error i am getting
Error: timed out waiting for at least 2 nodes to join the cluster and become ready in "Synopsys": context deadline exceeded

This is the YAML i am using:
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: synopsys-coverity-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0aa9bb5693a7c0cf6 }
      us-east-1b: { id: subnet-015329d3207246c28 }

nodeGroups:
  - name: Synopsys
    ami: ami-07aa3317551c8fd9e
    instanceType: t3.xlarge
    desiredCapacity: 2
    amiFamily: Ubuntu1804
    privateNetworking: true
    volumeSize: 120
    minSize: 2
    maxSize: 3
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh Synopsys_Coverity --kubelet-extra-args "--node-labels=$${NODE_LABELS}"
  - name: Coverity
    ami: ami-088c436a8500a51ab
    amiFamily: WindowsServer2019FullContainer
    volumeSize: 120
    privateNetworking: true
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.xlarge
    # overrideBootstrapCommand: |
    #   #!/bin/bash
    #   /etc/eks/bootstrap.sh Synopsys_Coverity
      `

**Comment by cPu1** [comment]
@yossisp1972 the arguments you've passed to the bootstrap script are incorrect. The first argument should be the cluster name, as in:

```yaml
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh synopsys-coverity-cluster --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

Alternatively,

```yaml
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ${CLUSTER_NAME}  --kubelet-extra-args "--node-labels=${NODE_LABELS}"
```

**Comment by yossisp1972** [comment]
Hi,

The issue is with the custom AMI. When using the basic yaml from the web site it works and the nodes are created.
When i try a custom AMI it fails on this timeoue error.
I even tried the ubuntu AMIs in this list https://cloud-images.ubuntu.com/aws-eks/

nothing seems to work. Is there anything needs to be done on the AMI itself?

**Comment by yuxiang-zhang** [comment]
https://github.com/eksctl-io/eksctl/issues/6058#issuecomment-1403236938 Based on this comment that I linked to above, the yaml aren't written to custom AMIs

**Comment by yossisp1972** [comment]
> [#6058 (comment)](https://github.com/eksctl-io/eksctl/issues/6058#issuecomment-1403236938) Based on this comment that I linked to above, the scripts aren't written to custom AMIs

Ok, now i am getting confused, so i dont need to add the overrideBootstrapCommand to the yaml file?
If i dont add it i am getting the errot that started that thread.
So which is it?

**Comment by yuxiang-zhang** [comment]
Does this help? https://eksctl.io/usage/custom-ami-support/?h=powershell#windows-custom-ami-support

**Comment by yossisp1972** [comment]
I was able to get the windows nodes working.
The issue i have now is linux, i have an ubuntu AMI that i want to use as a node.
How do i do that? i have read that AWS only supported Amazon Linux till now, but i found this

https://cloud-images.ubuntu.com/aws-eks/

However this also doesnt work and i am getting this time out
Error: timed out waiting for at least 2 nodes to join the cluster and become ready in "synopsys": context deadline exceeded

this is the YAML i am using

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: synopsys-cluster-test
  region: us-east-1

nodeGroups:
  - name: synopsys
    ami: ami-059ddc8b6b56cdf10
    amiFamily: Ubuntu1804
    volumeSize: 120
    # privateNetworking: true
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    instanceType: t3.2xlarge
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ${CLUSTER_NAME}  --kubelet-extra-args "--node-labels=${NODE_LABELS}"```
