### ISSUE TITLE
[Feature] Allow the Karpenter eksctl add-on to pass in `permissionBoundary`

### ISSUE THREAD

**Issue by jonathan-innis** [eksctl-io/eksctl#6839]
### What feature/behavior/change do you want?

Currently, the Karpenter add-on for eksctl will provision cloudformation that will spin up a NodeRole for an InstanceProfile that can used by the Karpenter IRSA role to provision nodes. Currently, this is provisioned automatically for users without any configuration. 

Some users that are installing Karpenter through this method are using roles or users in their accounts that have [delegated IAM permissions through permission boundaries](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html), effectively enforcing that every role that they create have a given permission boundary assigned to it. Karpenter should allow permission boundaries to be passed through the Karpenter add-on role, similar to how you are able to pass through a [`serviceRolePermissionBoundary`](https://eksctl.io/usage/schema/#iam-serviceRolePermissionsBoundary) and a [`serviceAccounts[*].permissionBoundary`](https://eksctl.io/usage/schema/#iam-serviceAccounts-permissionsBoundary).

### Why do you want this feature?

It's blocking users with delegated permission from deploying Karpenter through eksctl. They have to wire up all the CloudFormation themselves.

**Comment by srikanthgv88** [comment]
Looks like you have requested for similar feature where permission boundary should be defined for karpenter node role and karpenter controller roles created via eksctl.

[https://github.com/eksctl-io/eksctl/issues/6745](url)
