### ISSUE TITLE
[Bug] - MacOS timeout error

### ISSUE THREAD

**Issue by filipponova** [eksctl-io/eksctl#6849]
### What were you trying to accomplish?
When I run any `eksctl` commands in my Mac M1 Pro (Version 13.4.1 (c) - Ventura) I received the below error:

```bash
Error: could not create cluster provider from options: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error SSO: GetRoleCredentials, https response error StatusCode: 0, RequestID: , request send failed, Get "https://portal.sso.us-east-1.amazonaws.com/federation/credentials?account_id=XPTO&role_name=XPTO": dial tcp: lookup portal.sso.us-east-1.amazonaws.com: i/o timeout
```

In my case I'm try run the follow command:

```bash
eksctl utils associate-iam-oidc-provider --cluster $CLUSTER_NAME --approve --profile xpto
```

### What happened?
Received timeout error when runs any eksctl commands.
### How to reproduce it?

In a Mac running OSX Ventura 13.4.1

1 - Install eksctl (I'm using the version 0.150.0-dev)
2 - Try run any command in macOS. In my case this command: `eksctl utils associate-iam-oidc-provider --cluster $CLUSTER_NAME --approve --profile xpto`

**Logs**
```bash
Error: could not create cluster provider from options: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error SSO: GetRoleCredentials, https response error StatusCode: 0, RequestID: , request send failed, Get "https://portal.sso.us-east-1.amazonaws.com/federation/credentials?account_id=XPTO&role_name=XPTO": dial tcp: lookup portal.sso.us-east-1.amazonaws.com: i/o timeout
```

**Anything else we need to know?**

**Versions**

```
$ eksctl info

eksctl version: 0.150.0-dev
kubectl version: v1.27.4
OS: darwin
```

**Comment by yuxiang-zhang** [comment]
How did you configure your AWS credentials? Please refer to https://eksctl.io/introduction/#prerequisite

**Comment by filipponova** [comment]
@yuxiang-zhang, the issue is not related to my credentials, it's the communication between eksctl and the AWS STS API that's causing an issue. When I make requests manually, they are successful, but eksctl returns a timeout.

**Comment by filipponova** [comment]
Hello, Folks.

Any updates?

**Comment by yuxiang-zhang** [comment]
I cannot reproduce the issue, I suspect it's some conflict in your AWS credentials setup. Notice the URL that's used to fetch the credentials `https://portal.sso.us-east-1.amazonaws.com/federation/credentials?account_id=XPTO&role_name=XPTO`, the account ID doesn't look correct. Have you set any environment variables related to AWS credentials?

**Comment by filipponova** [comment]
I changed my account id to XPTO, just it. I won't paste my account id on internet.

**Comment by yuxiang-zhang** [comment]
I'm saying that I need more information so I can try to reproduce. You may need to share *how* you set up your credentials to help us help you
