### ISSUE TITLE
[Bug] Link doesn't point to as specified

### ISSUE THREAD

**Issue by Viveksati5143** [eksctl-io/eksctl#6857]
### What were you trying to accomplish?

The link in README.md>contributions> CNCF Code of Conduct doesn't point directly to CNCF Code of Conduct

### What happened?
It pointed to the link in eksctl first as shown in the screenshot:
![image](https://github.com/eksctl-io/eksctl/assets/100852245/7ec0cd23-cab4-4591-b58b-954d3daa9c9d)
It is not the right practice as it should directly point to CNCF Code of Conduct

### How to reproduce it?

Go to README.md>contributions> CNCF Code of Conduct

**Comment by cPu1** [comment]
Other projects like [Helm](https://github.com/helm/helm#code-of-conduct) also follow this practice, and eksctl is not a CNCF project.

**Comment by Viveksati5143** [comment]
> Other projects like [Helm](https://github.com/helm/helm#code-of-conduct) also follow this practice, and eksctl is not a CNCF project.

But my point was making the 2way process into 1 i.e directly it should open https://github.com/cncf/foundation/blob/main/code-of-conduct.md on clicking the link.
instead of first https://github.com/eksctl-io/eksctl/blob/main/CODE_OF_CONDUCT.md and then the above one.
