### ISSUE TITLE
[Feature] Support new Israeli AWS Region

### ISSUE THREAD

**Issue by odedia** [eksctl-io/eksctl#6896]
AWS announced today their new Israeli region, il-central-1.
However, eksctl cannot create clusters in this region. 
It appears this is just a validation check on the regions that were supported when the latest version of the CLI was released. 

It would be great to have support for eksctl in the new region.

Thanks!

![image](https://github.com/eksctl-io/eksctl/assets/2992180/2284d338-6fa9-49e8-ae08-d796f5babdae)

**Comment by cPu1** [comment]
Hi @odedia. Thanks for bringing this to our notice. I have opened a [PR](https://github.com/eksctl-io/eksctl/pull/6899), it'll go out this week. New regions do not usually go out on the launch day in eksctl.
