### ISSUE TITLE
[Bug] Fix Merge release changes to main workflow

### ISSUE THREAD

**Issue by Himangini** [eksctl-io/eksctl#6902]
### Description
https://github.com/eksctl-io/eksctl/actions/workflows/release-merge.yaml

The merge release changes workflow keeps failing with `fatal: There is no merge in progress (MERGE_HEAD missing).` when there are no changes to merge. We need to fix this failure.

**Comment by Himangini** [comment]
Related https://github.com/eksctl-io/eksctl-private/issues/1180

**Comment by tungbq** [comment]
Is this issue only open for internal submission? I don't have access to this repo to see the change that might cause the issue: https://github.com/eksctl-io/eksctl-private/issues/1180
