### ISSUE TITLE
Documentation variations between eksctl.io and github.com

### ISSUE THREAD

**Issue by pgasca** [eksctl-io/eksctl#6971]
### What were you trying to accomplish?

My expectation was that the installation instructions in these two places would be identical:
* https://eksctl.io/introduction/#installation
* https://github.com/eksctl-io/eksctl#installation

My request is to make sure that any redundant information in both places should be an automated mirror of one another. Or if they are managed manually, information should go in one place and linked to by the others site to avoid references going out of sync.

### What happened?

https://eksctl.io/introduction/#installation
has a Prerequisite section that is missing in:
https://github.com/eksctl-io/eksctl#installation

### How to reproduce it?

Compare:
* https://eksctl.io/introduction/#installation
* https://github.com/eksctl-io/eksctl#installation

**Logs**

N/A

**Anything else we need to know?**

This is just one example of possible variation between sources. If there is no way to automate syncing the info between them, my recommendation would be to have the readme on GitHub side point to https://eksctl.io or vice versa, and remove any duplicate information, to avoid things going out of sync and to allow for easier maintenance.

**Versions**

```
$ eksctl info
```

**Comment by TiberiuGC** [comment]
Hi @pgasca , the prerequisites section is present on Github as-well
https://github.com/eksctl-io/eksctl#prerequisite

We may consider changing its position for consistency, or using links. We'll discuss this internally.

**Comment by Himangini** [comment]
I have updated the readme here https://github.com/eksctl-io/eksctl/pull/7092 so both our documentation and Github instructions follow the same order.

**Comment by pgasca** [comment]
Thank you!
