### ISSUE TITLE
[Bug] CoreDNS out of date/support/recommendation

### ISSUE THREAD

**Issue by AndrewFarley** [eksctl-io/eksctl#7002]
### What were you trying to accomplish?
Deploying/updating an EKS cluster via EKSCTL and installing the "utils" supported.  Unfortunately, the embedded coredns versions/builds for every supported version of EKS are out of date according to Amazon's documentation on recommended CoreDNS versions.

Reference: https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html#coredns-versions

* 1.23 is currently [coredns:v1.8.7-eksbuild.2](https://github.com/eksctl-io/eksctl/blob/5a416eed1657930c1b313ff6bd9c7850b3834ab4/pkg/addons/default/assets/coredns-1.23.json#L172), should be v1.8.7-eksbuild.7
* 1.24 is currently [coredns:v1.8.7-eksbuild.3](https://github.com/eksctl-io/eksctl/blob/5a416eed1657930c1b313ff6bd9c7850b3834ab4/pkg/addons/default/assets/coredns-1.24.json#L173), should be v1.9.3-eksbuild.6
* 1.25 is currently [coredns:v1.9.3-eksbuild.2](https://github.com/eksctl-io/eksctl/blob/5a416eed1657930c1b313ff6bd9c7850b3834ab4/pkg/addons/default/assets/coredns-1.25.json#L173), should be v1.9.3-eksbuild.6
* 1.26 is currently [coredns:v1.9.3-eksbuild.2](https://github.com/eksctl-io/eksctl/blob/5a416eed1657930c1b313ff6bd9c7850b3834ab4/pkg/addons/default/assets/coredns-1.26.json#L173), should be v1.9.3-eksbuild.6
* 1.27 is currently [coredns:v1.10.1-eksbuild.1](https://github.com/eksctl-io/eksctl/blob/5a416eed1657930c1b313ff6bd9c7850b3834ab4/pkg/addons/default/assets/coredns-1.27.json#L173), should be v1.10.1-eksbuild.3

_EDIT Sep 13 Updated versions from URL_

**Comment by Himangini** [comment]
Related to #6999 Update aws-node workflow needs to be fixed

**Comment by Himangini** [comment]
Spike to understand how much work is involved with automation pov
Outcome - document findings here
Timebox - 1-2 days
