### ISSUE TITLE
eksctl cli Error: getting nodegroup's kubernetes version: failed to list nodes: Unauthorized

### ISSUE THREAD

**Issue by rluan** [eksctl-io/eksctl#7048]
I created EKS cluster with eksctl, with AWS IAM account: TEST-A, all works fine.

I have another AWS IAM user "REAL-B" with IAM "AdministratorAccess" permission, and this user is in a preset role within EKS, has admin permissions as well.
```
$ kubectl get cm aws-auth -n kube-system
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::XXXXX:role/EKSAdminRole
      username: admin
```
but to use this IAM user to interact with eksctl has some issues. as below descriptions:

### 1  update the kubectl context
`aws eks update-kubeconfig --region us-east-1 --name eng-np-eks --role-arn "arn:aws:iam::XXXXX:role/EKSAdminRole"
`

### 2 show kubectl permissions
```
$ kubectl auth can-i --list
Resources                                       Non-Resource URLs   Resource Names   Verbs
*.*                                             []                  []               [*]
                                                [*]                 []               [*]
selfsubjectreviews.authentication.k8s.io        []                  []               [create]
selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
                                                [/api/*]            []               [get]
                                                [/api]              []               [get]
                                                [/apis/*]           []               [get]
                                                [/apis]             []               [get]
                                                [/healthz]          []               [get]
                                                [/healthz]          []               [get]
                                                [/livez]            []               [get]
                                                [/livez]            []               [get]
                                                [/openapi/*]        []               [get]
                                                [/openapi]          []               [get]
                                                [/readyz]           []               [get]
                                                [/readyz]           []               [get]
                                                [/version/]         []               [get]
                                                [/version/]         []               [get]
                                                [/version]          []               [get]
                                                [/version]          []               [get]

```

### 3 issue is here
```
$ eksctl get cluster
NAME            REGION          EKSCTL CREATED
eng-np-eks      us-east-1       True

$ eksctl get nodegroup -c eng-np-eks
Error: getting nodegroup's kubernetes version: failed to list nodes: Unauthorized

$ eksctl info
eksctl version: 0.154.0
kubectl version: v1.27.0
OS: linux

```

**Comment by cPu1** [comment]
eksctl does read any kubeconfig files from the filesystem, so any writes to the authenticator config made by `aws eks update-kubeconfig` will not be seen by eksctl. Before running any eksctl commands, you need to either use credentials from `aws sts assume-role --role-arn "arn:aws:iam::XXXXX:role/EKSAdminRole"`,  or configure your AWS CLI (`~/.aws`) to assume that role by setting `role_arn` in your AWS profile config, as in:

```
# ~/.aws/config
[profile eks-admin]
source_profile=<base-profile>
role_arn= arn:aws:iam::XXXXX:role/EKSAdminRole
```

The role should also have [these policies](https://eksctl.io/usage/minimum-iam-policies/) attached.

**Comment by rluan** [comment]
I still can not make it work with above suggestions. I think this issue can be reproduced easy with two different admin IAM users account...

**Comment by rluan** [comment]
an update:
1, use "configure your AWS CLI (~/.aws) " not works for me, maybe some syntax issue ? I need to check more 
2, use "aws sts assume-role --role-arn" can work.

steps:
aws sts assume-role --role-arn "arn:aws:iam::xxxx:role/eng-np-eksPSTAdminRole" --role-session-name tempeks

export AWS_ACCESS_KEY_ID="xxxx"
export AWS_SECRET_ACCESS_KEY="xxxx"
export AWS_SESSION_TOKEN="xxxx"
export AWS_DEFAULT_REGION=us-east-1

Returns:
{ 
    "UserId": "xxxx:tempeks",
    "Account": "xxxx",
    "Arn": "arn:aws:sts::xxxx:assumed-role/eng-np-eksPSTAdminRole/tempeks"
}

aws eks update-kubeconfig --region us-east-1 --name eng-np-eks
Added new context arn:aws:eks:us-east-1:xxxx:cluster/eng-np-eks to /home/rluan/.kube/config

$ eksctl get cluster
NAME            REGION          EKSCTL CREATED
eng-np-eks      us-east-1       True
$ eksctl get nodegroup -c eng-np-eks
CLUSTER         NODEGROUP       STATUS          CREATED                 MIN SIZE        MAX SIZE        DESIRED CAPACITY        INSTANCE TYPE   IMAGE ID                ASG NAME        TYPE
eng-np-eks      proxy-v1        CREATE_COMPLETE 2023-09-04T07:57:24Z    1               3               3                       m5.large        ami-032a4564f2f4ba130   eksctl-eng-np-eks-nodegroup-proxy-v1-NodeGroup-11RXADV2H6B9U     unmanaged
eng-np-eks      worker-v1       CREATE_COMPLETE 2023-09-04T07:54:10Z    1               3               1                       m5.2xlarge      ami-032a4564f2f4ba130   eksctl-eng-np-eks-nodegroup-worker-v1-NodeGroup-TEHR20YJLXA      unmanaged

**Comment by rluan** [comment]
another concern is , i'm using IAM  admin user  already, why still gives error say no permissions?
```
# eksctl get nodegroup -c eng-np-eks
Error: getting nodegroup's kubernetes version: failed to list nodes: Unauthorized
```
this also resolved as:
edit configmap aws-auth, add the IAM user mappings specifically.
```
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::xxxx:user/REAL-B
      username: admin
```
hope can help those who has the same issues.
