### ISSUE TITLE
[Feedback] eksctl - The official CLI for Amazon EKS - /

### ISSUE THREAD

**Issue by Ejoumalai** [eksctl-io/eksctl#7085]
not clearly explained  how to install in windows 10, The default version is installing i.e is 0, .22 eks cluster is not creating , throwing error

**Comment by a-hilaly** [comment]
Hi @Ejoumalai !Tthank you for reporting this. Are you currently following the steps mentioned in https://eksctl.io/introduction/#for-windows ?

**Comment by Himangini** [comment]
> Hi @Ejoumalai !Tthank you for reporting this. Are you currently following the steps mentioned in https://eksctl.io/introduction/#for-windows ?

@Ejoumalai can you provide more context on what installation steps you are following?
