### ISSUE TITLE
[Help] Documentation missing "eksctl update iamserviceaccount" usage

### ISSUE THREAD

**Issue by trombini77** [eksctl-io/eksctl#7086]
I had to update the IAM Policy of AWS ALB Controller because it is necessary, see https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.7

But to associate a new Policy to an already Service Account created by `eksctl create iamserviceaccount` following the AWS ALB Controller documentation, only repeating the installation block with the new Policy ARN:

```
eksctl create iamserviceaccount \
  --cluster=CLUSTER_NAME \
  --region REGION \
  --namespace=NAMESPACE \
  --name=aws-load-balancer-controller \
  --attach-policy-arn=arn:aws:iam::ACCOUNT_ID:policy/AWSLoadBalancerControllerIAMPolicyNew \
  --override-existing-serviceaccounts \
  --approve
```

will returns, for example:
```
2023-09-19 23:13:19 [ℹ]  6 existing iamserviceaccount(s) (cert-manager/cert-manager,default/external-dns,default/loki-s3,kube-system/aws-load-balancer-controller,kube-system/ebs-csi-controller-sa,observability/aws-alb-log-exporter) will be excluded
2023-09-19 23:13:19 [ℹ]  1 iamserviceaccount (kube-system/aws-load-balancer-controller) was excluded (based on the include/exclude rules)
2023-09-19 23:13:19 [!]  metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
2023-09-19 23:13:19 [ℹ]  no tasks
```

and no changes were made.

I used the following command:

```
eksctl update iamserviceaccount \
  --cluster=CLUSTER_NAME \
  --region REGION \
  --namespace=NAMESPACE \
  --name=aws-load-balancer-controller \
  --attach-policy-arn=arn:aws:iam::ACCOUNT_ID:policy/AWSLoadBalancerControllerIAMPolicyNew \
  --approve
```

and it worked fine.

So or I didn´t find in the documentation the `eks update iamserviceaccount` or it´s not there.
Reference: https://eksctl.io/usage/iamserviceaccounts/

**Comment by a-hilaly** [comment]
Hi @trombini77 ! Thanks for creating a help ticket. I will do some research and get back to you asap! In the mean time, I wonder if you did a role name update, using something like `aws iam update-role` (https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateRole.html)

**Comment by cPu1** [comment]
@trombini77, this is documented on the page you linked to, right above the [Usage with config files](https://eksctl.io/usage/iamserviceaccounts/#usage-with-config-files) section, but I do agree that the documentation could benefit from more examples of `eksctl update iamserviceaccount`. 

>To update a service accounts roles permissions you can run eksctl update iamserviceaccount.
