### ISSUE TITLE
Bump github.com/emicklei/go-restful/v3 version to v3.10.0

### ISSUE THREAD

**Issue by Bjyothi2023** [eksctl-io/eksctl#7119]
An vulnerability has been reported because of "github.com/emicklei/go-restful/v3" version v3.9.0 .

Vulnerability reported: PRISMA-2022-0227
Affected package : github.com/emicklei/go-restful/v3
Affected version reported : v3.9.0
Fixed version reported by scanner : v3.10.0
Eksctl version used: v0.159.0

Hence requesting team to upgrade "github.com/emicklei/go-restful/v3" from v3.9.0 to v3.10.0

**Comment by Himangini** [comment]
@Bjyothi2023 do you not see this option here https://github.com/eksctl-io/eksctl/issues/new/choose? 🤔 
![Screenshot 2023-09-28 at 17 48 52](https://github.com/eksctl-io/eksctl/assets/10995114/1f607edc-8c95-438f-8de3-f882246d7136)

**Comment by cPu1** [comment]
Closed by #7121. The fix will be out in the next release candidate.
