### ISSUE TITLE
[Bug] eksctl utils update-coredns image interpolation broken

### ISSUE THREAD

**Issue by Guillermogsjc** [eksctl-io/eksctl#7125]
when deploying k8s 1.28 with eksctl v0.160.0, coredns will not arrive because of `Error: InvalidImageName`, with a more specific message:

Failed to apply default image tag "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.10.1-eksbuild.3%!(EXTRA string=602401143452, string=eu-west-1, string=amazonaws.com)": couldn't parse image name "602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.10.1-eksbuild.3%!(EXTRA string=602401143452, string=eu-west-1, string=amazonaws.com)": invalid reference format

looks like an issue related with string interpolation  on the image name

![image](https://github.com/eksctl-io/eksctl/assets/10863848/92668a5e-458f-4fc9-ac97-ea3b03169718)

I can see two replicasets created for coredns, one with that bad interpolated image name

![image](https://github.com/eksctl-io/eksctl/assets/10863848/14cfbb8d-7d6d-4b3f-8c7f-f047321da644)

I guess that this command

`eksctl utils update-coredns --approve --cluster ${CLUSTER_NAME}`

that it is being executed in the pipeline right after creation of nodegroups, is patching the image name with the bad interpolated string.

eksctl version: 0.160.0
kubectl version: v1.28.1-eks-43840fb
OS: linux

**Comment by Himangini** [comment]
@Guillermogsjc thanks for reporting the issue, I have added a [PR](https://github.com/eksctl-io/eksctl/pull/7126) to fix this error.

**Comment by Himangini** [comment]
The PR is merged, we'll release the changes soon.

**Comment by AdamDomagalsky** [comment]
same issue with _eksctl: 0.161.0, EKS: v1.28.1-eks-43840fb_
`602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.10.1-eksbuild.3%!(EXTRA
          string=602401143452, string=eu-west-1, string=amazonaws.com)` as workaround I've replaced _**coredns** deployment_ to `602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/coredns:v1.10.1-eksbuild.1`

**Comment by cPu1** [comment]
> same issue with _eksctl: 0.161.0, EKS: v1.28.1-eks-43840fb_ `602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/eks/coredns:v1.10.1-eksbuild.3%!(EXTRA string=602401143452, string=eu-west-1, string=amazonaws.com)` as workaround I've replaced _**coredns** deployment_ image to `602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/coredns:v1.10.1-eksbuild.3`

@AdamDomagalsky, the fix was released in https://github.com/eksctl-io/eksctl/releases/tag/v0.162.0-rc.0, and not 0.161.0.
