### ISSUE TITLE
[Help] not able to create a node group using eksctl

### ISSUE THREAD

**Issue by DarshanSohaliya** [eksctl-io/eksctl#7136]
### What help do you need?

When I try to create a new node group i get this error

```2023-10-03 13:41:44 [ℹ]  will use version 1.27 for new nodegroup(s) based on control plane version
2023-10-03 13:41:44 [!]  no eksctl-managed CloudFormation stacks found for "gds-cluster", will attempt to create nodegroup(s) on non eksctl-managed cluster
Error: getting list of API resources for raw REST client: Unauthorized
```

**Comment by cPu1** [comment]
> Are you able to interact with your cluster using kubectl? You'll need to ensure that your AWS identity has access to the cluster. More information can be found in [Manage IAM users and roles](https://eksctl.io/usage/iam-identity-mappings/?h=iamidentity#manage-iam-users-and-roles).

@DarshanSohaliya please let us know if you have any more questions otherwise this issue will be closed automatically.
