### ISSUE TITLE
Note able to scale node group due to naming convention of nodegroup

### ISSUE THREAD

**Issue by togunsanya** [eksctl-io/eksctl#7137]
### What were you trying to accomplish?

I am trying to scale nodegroup with the help of eksctl (latest version)
### What happened?

While running 
```
eksctl scale nodegroup --cluster=abc-sandbox-eks-devops-0 --name=abc-sandbox-eks-ng-high_0 --nodes=0 --nodes-max=1 --nodes-min=0
```
I am getting below error:

```
Error: validation for abc-sandbox-eks-ng-high_0 failed, name must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
```
I have checked AWS official documentation and as per the documentation underscore underscore (_) is allowed in nodegroup names

https://docs.aws.amazon.com/eks/latest/userguide/create-managed-node-group.html

**Comment by TiberiuGC** [comment]
Hi @togunsanya , for a wide range of commands `eksctl` operates on top of CloudFormation API. Thus, for UX consistency, we want to have the supported nodegroup names aligned to CFN rules. For this case it means we won't accept `_` as part of the ng name, even if it's supported in EKS.
