### ISSUE TITLE
Remove EKS cluster role inline policies because these are no longer needed

### ISSUE THREAD

**Issue by youwalther65** [eksctl-io/eksctl#7139]
### What feature/behavior/change do you want?
eksctl by default creates a cluster IAM role which contain two custom inline IAM policies called "eksctl-xxx-cluster-PolicyCloudWatchMetrics" to allow "cloudwatch:PutMetricData" and "eksctl-xxx-cluster-PolicyELBPermissions" to allow three EC2 API related calls "ec2:DescribeAccountAttributes", "ec2:DescribeAddresses" and "ec2:DescribeInternetGateways"

These IAM policies are no longer needed.

### Why do you want this feature?
eksctl already attaches the AWS managed IAM policy [AmazonEKSClusterPolicy](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEKSClusterPolicy.html) which contains all permission from custom inline policy "eksctl-xxx-cluster-PolicyELBPermissions". So we can safely remove "eksctl-xxx-cluster-PolicyELBPermissions".

"eksctl-xxx-cluster-PolicyCloudWatchMetrics" custom inline policy was introduced to solve issue [CloudWatch Metrics for AWS CNI plugin #278](https://github.com/eksctl-io/eksctl/issues/278). Pushing CNI metrics to CloudWatch is part of worker node responsibility and has nothing to do with control plane and EKS cluster policy. Using least privilege AWS recommends using _IAM roles for service account (IRSA)_ , which is possible for AWS VPC CNI as well. So there is even no need to put this policy on worker nodes but rather make this part of AWS VPC CNI IRSA role. So we can drop "eksctl-xxx-cluster-PolicyCloudWatchMetrics" as well.

**Comment by ibnjunaid** [comment]
@yuxiang-zhang Can you please assign this issue to me

**Comment by yuxiang-zhang** [comment]
@ibnjunaid Thank you for signing up!
