### ISSUE TITLE
Issue: Getting below error while creating 'iamserviceaccount'.

### ISSUE THREAD

**Issue by AkashTripathi98** [eksctl-io/eksctl#7200]
Hi Folks,

I have created a Eks cluster and iam create-policy without any error but getting problem while creating 'iamserviceaccount'. I have tried several options but getting same below error.
I am using the below cmd to create the iamserviceaccount:
` eksctl create iamserviceaccount    --name ebs-csi-controller-sa  --namespace kube-system --region ap-south-1 --cluster TestSymphony1  --role-name AmazonEKS_EBS_CSI_DriverRole  --role-only  --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicyN  --approve`.

![image](https://github.com/eksctl-io/eksctl/assets/50174766/be452f66-7bc5-45e3-844a-12494df25c1b)
I am stuck at this point and your guidance on this would be much appreciated.

**Comment by AkashTripathi98** [comment]
Thanks for your prompt response. Looking forward to get some insight on this.

**Comment by Himangini** [comment]
@AkashTripathi98 have you checked the Cloudformation console for any errors? you can also use `eksctl utils describe-stacks --help` to view more information on the Cloudformation stack for your cluster.
