### ISSUE TITLE
[Bug] Documentation points to bottlerocket-os/bottlerocket

### ISSUE THREAD

**Issue by stockholmux** [eksctl-io/eksctl#7346]
### What happened?

Looking at the [eksctl documentation,](https://eksctl.io/usage/schema/#nodeGroups-bottlerocket-settings) it refers to bottlerocket-os/bottlerocket github repo for documentation. These links lead readers to github README that then further connects them to the [current documentation ](https://bottlerocket.dev/en/) (i.e. it's an outdated link).

### How to reproduce it?

1. go to https://eksctl.io/usage/schema/#nodeGroups-bottlerocket-settings
2. Click on "[bottlerocket settings](https://github.com/bottlerocket-os/bottlerocket/#description-of-settings)" this leads to a place that just tells you to go to https://bottlerocket.dev/en/os/latest/#/api/settings/

**Logs**

n/a 
**Anything else we need to know?**

Glad to submit a PR to fix this. It seems like this link is in https://github.com/eksctl-io/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/assets/schema.json#L1779, but I'm not 100% sure.

**Comment by TiberiuGC** [comment]
Hi @stockholmux - what link do you reckon `eksctl` should be pointing to?

Also, my understanding is that Bottlerocket github README is pointing to an outdated link? Thus, isn't this something they should update on their end? We can ofc update the reference on our end if needed but I'm trying to understand the issue.

**Comment by TiberiuGC** [comment]
Hi @stockholmux - what link do you reckon eksctl should be pointing to?

**Comment by stockholmux** [comment]
@TiberiuGC the eksctl documentation should point directly to https://bottlerocket.dev/en/os/latest/#/api/settings/ instead of anything on the Bottlerocket readme as it currently does.
