### ISSUE TITLE
[Bug] No longer support kube api > v1.22

### ISSUE THREAD

**Issue by rmeyssonnier** [eksctl-io/eksctl#7347]
### What were you trying to accomplish?

Install VPC controllers for windows support in cluster

### What happened?

Error message : Error: error installing VPC controller: creating CertificateSigningRequest: constructing REST client mapping for certificates.k8s.io/v1beta1, Kind=CertificateSigningRequest: no matches for kind "CertificateSigningRequest" in versions ["certificates.k8s.io/" "certificates.k8s.io/v1beta1"]

### How to reproduce it?

Use a kube cluster with api > v1.22 and try to run command : eksctl utils install-vpc-controllers

**Logs**

![Capture d’écran 2023-12-03 à 13 26 00](https://github.com/eksctl-io/eksctl/assets/25454720/e32f5f7d-5a09-464d-bbb7-36e030875da4)

**Anything else we need to know?**

**Versions**

```
eksctl version: 0.165.0-dev+2064e6b32.2023-11-28T17:59:03Z
kubectl version: v1.26.2
OS: darwin```

**Comment by worldhopper** [comment]
Seeing the same issue as well. Can the issue be reopened?
