### ISSUE TITLE
[Help] Updating existing serviceaccounts with the --override-existing-serviceaccounts flag does not work

### ISSUE THREAD

**Issue by mo-rieger** [eksctl-io/eksctl#7348]
### What were you trying to accomplish?

Update an existing Kubernetes ServiceAccount to map to the IAM Role created by eksctl.

### What happened?

To create and update IAMServiceAccounts, we run `eksctl create iamserviceacount --override-existing-serviceaccounts` in CI. This results in `no tasks` when all ServiceAccounts already exists. I assume this should overwrite all existing ServiceAccounts because of the `override-existing-serviceaccounts` flag beeing set.

### How to reproduce it?

1. Create a plain ServiceAccount in Kubernetes.
2. Add iam configuration to your ClusterConfig file:

```yaml
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: my-sa
        namespace: my-sa-test
      attachPolicyARNs:
        - "arn:aws:iam::1234546789:policy/cluster-my-sa-policy"
```

 3. Run `eksctl create iamserviceacount -f config.json --override-existing-serviceaccounts`

**Logs**

```
$ eksctl create iamserviceaccount -f config.json --override-existing-serviceaccounts
2023-12-01 16:55:03 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2023-12-01 16:55:03 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2023-12-01 16:55:03 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2023-12-01 16:55:03 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2023-12-01 16:55:05 [ℹ]  8 existing iamserviceaccount(s) (aws-load-balancer-controller/aws-loadbalancer-controller,cloudwatch-exporter/cloudwatch-exporter,cluster-autoscaler/cluster-autoscaler,external-dns/external-dns,kube-system/aws-node,kube-system/cilium-operator,kubecost/kubecost-cost-analyzer,opencost/opencost) will be excluded
2023-12-01 16:55:05 [ℹ]  5 iamserviceaccounts (aws-load-balancer-controller/aws-loadbalancer-controller, cloudwatch-exporter/cloudwatch-exporter, external-dns/external-dns, kube-system/cilium-operator, opencost/opencost) were excluded (based on the include/exclude rules)
2023-12-01 16:55:05 [!]  metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
2023-12-01 16:55:05 [ℹ]  no tasks
```
**Anything else we need to know?**

When looking at the code, regardless of the `--override-existing-serviceaccounts` flag beeing set, all existing SA are excluded by the [SetExcludeExistingFilter](https://github.com/eksctl-io/eksctl/blob/83ae2fd7e46da5a825a112b53a627231020e653c/pkg/ctl/create/iamserviceaccount.go#L113).

**Versions**

```
$ eksctl info
eksctl version: 0.150.0-dev+cdcf906b7.2023-07-20T12:35:52Z
kubectl version: v1.27.1
OS: darwin
```

**Comment by TiberiuGC** [comment]
> To create and update IAMServiceAccounts, we run eksctl create iamserviceacount --override-existing-serviceaccounts in CI

To update role permissions for an existing `iamserviceaccount` you should use `eksctl update iamserviceaccount`.

> When looking at the code, regardless of the --override-existing-serviceaccounts flag beeing set, all existing SA are excluded by the [SetExcludeExistingFilter](https://github.com/eksctl-io/eksctl/blob/83ae2fd7e46da5a825a112b53a627231020e653c/pkg/ctl/create/iamserviceaccount.go#L113).

Checking filter's logic AND since you set `--override-existing-serviceaccounts`, it's only this 👇  section of logic that could have caused your service accounts to be excluded.

https://github.com/eksctl-io/eksctl/blob/0e874c18274f7aa767800528acbafbfb0384c0ae/pkg/ctl/cmdutils/filter/iamserviceaccount_filter.go#L55-L58

This suggest that a CloudFormation stack for the IAM Role already exists. Have you previously created the role using `eksctl create iamserviceaccount --role-only`? If so, you should be manually setting the role ARN annotation (i.e. `"eks.amazonaws.com/role-arn": "role-arn"` on the service account (as per this 👇  docs section) https://github.com/eksctl-io/eksctl/blob/0e874c18274f7aa767800528acbafbfb0384c0ae/userdocs/src/usage/iamserviceaccounts.md?plain=1#L73-L74

**Comment by TiberiuGC** [comment]
Also, if you fancy, `eksctl` version [0.165.0](https://github.com/eksctl-io/eksctl/releases/tag/v0.165.0) has added support for  [EKS Pod Identity Associations](https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/), meant to bring several improvements over current iam service accounts implementation. Feel encouraged to try it out.

Docs here - https://eksctl.io/usage/pod-identity-associations/

**Comment by mo-rieger** [comment]
Thanks for your detailed answer, @TiberiuGC.
So I guess what happened is that things got mixed up on my end of things.

1. The SA was managed by Helm, who immediately reverted the changes Ekcsctl was doing on the SA.
2. When I removed the SA creation from the helm, the CloudFormation Stack for IAM already existed, and therefore eksctl did not create the SA. 

Is this the intended behaviour that it just checks for the cloud formation stack and not for the existence of the ServiceAccount in Kubernetes itself? If so, the issue can be closed.

**Comment by TiberiuGC** [comment]
Yes, the expectation is that if CFN stack exists, the `iamserviceaccount` is already correctly configured. The annotation on service account being either added previously by `eksctl` or by some other tool. Thus,  creation for the `iamserviceaccount` in question will be skipped, regardless what flags are specified.
