### ISSUE TITLE
[Feature] Add Support For EKS Access Entry API 

### ISSUE THREAD

**Issue by jonathan-innis** [eksctl-io/eksctl#7425]
### What feature/behavior/change do you want?

EKS just released the Access Entry API which allows you to manage your access control management for users to the cluster through IAM roles through a separate API service rather than through the ConfigMap that currently exists on the cluster today: https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/. 

It would be really nice to see this support first-classed in eksctl so that we can start using the new mechanism when spinning up clusters using `ClusterConfig` rather than using the current ConfigMap mechanism.

### Why do you want this feature?

It's the latest and greatest way to do IAM role to Kubernetes user management on EKS clusters

**Comment by cPu1** [comment]
We are aware and have merged the PRs for supporting EKS Access Entries. A release candidate will be out shortly.

**Comment by jonathan-innis** [comment]
Perfect @cPu1 Thanks for the update! Didn't look through the merged PRs, just saw that there wasn't a release yet. Excited to try out the RC.

**Comment by cPu1** [comment]
This is out in https://github.com/eksctl-io/eksctl/releases/tag/v0.167.0.
