### ISSUE TITLE
eksctl now panics out of the blue

### ISSUE THREAD

**Issue by Paddy-CH** [eksctl-io/eksctl#7479]
I've been using eksctl whilst developing a eks/fargate deployment. During this time I have created and deleted a cluster using eksctl and a yaml file. This yaml file has not changed, so not sure why it now fails. I did clean up the aws sandbox account.

This is the panic. I happens just after it creates the fargate profile.
`panic: assignment to entry in nil map

goroutine 186 [running]:
github.com/weaveworks/eksctl/pkg/fargate/coredns.scheduleOnFargate({0x64aaf10?, 0xc00073e480?})
        github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:122 +0xd5
github.com/weaveworks/eksctl/pkg/fargate/coredns.ScheduleOnFargate({0x64aaf10?, 0xc00073e480?})
        github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:109 +0x27
github.com/weaveworks/eksctl/pkg/eks.ScheduleCoreDNSOnFargateIfRelevant(0xc000debe80?, 0xc000c55c50, {0x64aaf10, 0xc00073e480})
        github.com/weaveworks/eksctl/pkg/eks/fargate.go:125 +0x105
github.com/weaveworks/eksctl/pkg/eks.(*fargateProfilesTask).Do(0xc0012e5800, 0x0?)
        github.com/weaveworks/eksctl/pkg/eks/fargate.go:57 +0x1cc
github.com/weaveworks/eksctl/pkg/utils/tasks.doSingleTask(0x0?, {0x646e190, 0xc0012e5800})
        github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:192 +0xe6
github.com/weaveworks/eksctl/pkg/utils/tasks.doSequentialTasks(0xc000177758?, {0xc00121d5e0, 0x2, 0xc000bc27e0?})
        github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:222 +0x6a
created by github.com/weaveworks/eksctl/pkg/utils/tasks.(*TaskTree).Do
        github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:152 +0x1aa`

Can anyone advise as to what I've done wrong?

**Comment by a-hilaly** [comment]
Hi @Paddy-CH - can you provide the yaml file you used to create the cluster?

**Comment by a-hilaly** [comment]
I was able to replicate your issue @Paddy-CH - working a fix that we can ship in `0.168`

**Comment by JPBM135** [comment]
I'm experiencing this too, same error!

**Comment by cabeaulac** [comment]
Failing for me now too.
Deploy command
```
eksctl create cluster --name $(CLUSTER_NAME) --region $(CLUSTER_REGION) --version 1.28 --fargate
```
Result
```
2024-01-16 07:13:24 [ℹ]  waiting for CloudFormation stack "eksctl-lseks-cluster"
2024-01-16 07:15:26 [ℹ]  creating Fargate profile "fp-default" on EKS cluster "lseks"
2024-01-16 07:17:37 [ℹ]  created Fargate profile "fp-default" on EKS cluster "lseks"
panic: assignment to entry in nil map

goroutine 139 [running]:
github.com/weaveworks/eksctl/pkg/fargate/coredns.scheduleOnFargate({0x106627930?, 0x14000a77080?})
	github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:122 +0xf8
github.com/weaveworks/eksctl/pkg/fargate/coredns.ScheduleOnFargate({0x106627930?, 0x14000a77080?})
	github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:109 +0x24
github.com/weaveworks/eksctl/pkg/eks.ScheduleCoreDNSOnFargateIfRelevant(0x1400017fe60?, 0x14000a52180, {0x106627930, 0x14000a77080})
	github.com/weaveworks/eksctl/pkg/eks/fargate.go:125 +0x104
github.com/weaveworks/eksctl/pkg/eks.(*fargateProfilesTask).Do(0x14000d1d300, 0x0?)
	github.com/weaveworks/eksctl/pkg/eks/fargate.go:57 +0x178
github.com/weaveworks/eksctl/pkg/utils/tasks.doSingleTask(0x140000cdfa8?, {0x1065ee448, 0x14000d1d300})
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:192 +0xd8
github.com/weaveworks/eksctl/pkg/utils/tasks.doSequentialTasks(0x0?, {0x1400091ac80, 0x2, 0x0?})
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:222 +0x6c
created by github.com/weaveworks/eksctl/pkg/utils/tasks.(*TaskTree).Do
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:152 +0x1b8
make: *** [aws-setup-cluster] Error 2
```

**Comment by cabeaulac** [comment]
Failed with `eksctl` 0.166.0 also. 
Command
```
eksctl create cluster --name lseks --region us-west-2 --version 1.28 --fargate
2024-01-16 07:59:36 [ℹ]  eksctl version 0.166.0
```
Results
```
2024-01-16 08:08:40 [ℹ]  waiting for CloudFormation stack "eksctl-lseks-cluster"
2024-01-16 08:09:40 [ℹ]  waiting for CloudFormation stack "eksctl-lseks-cluster"
2024-01-16 08:11:42 [ℹ]  creating Fargate profile "fp-default" on EKS cluster "lseks"
2024-01-16 08:16:00 [ℹ]  created Fargate profile "fp-default" on EKS cluster "lseks"
panic: assignment to entry in nil map

goroutine 230 [running]:
github.com/weaveworks/eksctl/pkg/fargate/coredns.scheduleOnFargate({0x109a598f0?, 0x14000bcc300?})
	github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:122 +0xf8
github.com/weaveworks/eksctl/pkg/fargate/coredns.ScheduleOnFargate({0x109a598f0?, 0x14000bcc300?})
	github.com/weaveworks/eksctl/pkg/fargate/coredns/coredns.go:109 +0x24
github.com/weaveworks/eksctl/pkg/eks.ScheduleCoreDNSOnFargateIfRelevant(0x14000151e60?, 0x140009e4fc0, {0x109a598f0, 0x14000bcc300})
	github.com/weaveworks/eksctl/pkg/eks/fargate.go:125 +0x104
github.com/weaveworks/eksctl/pkg/eks.(*fargateProfilesTask).Do(0x140004669c0, 0x0?)
	github.com/weaveworks/eksctl/pkg/eks/fargate.go:57 +0x178
github.com/weaveworks/eksctl/pkg/utils/tasks.doSingleTask(0x0?, {0x109a20598, 0x140004669c0})
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:189 +0xd8
github.com/weaveworks/eksctl/pkg/utils/tasks.doSequentialTasks(0x0?, {0x14000329120, 0x2, 0x1400019c000?})
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:219 +0x6c
created by github.com/weaveworks/eksctl/pkg/utils/tasks.(*TaskTree).Do
	github.com/weaveworks/eksctl/pkg/utils/tasks/tasks.go:149 +0x1b8
make: *** [aws-setup-cluster] Error 2
chadbeaulac@ChadsM2MBP localstack-on-eks % eksctl version
0.166.0
```

**Comment by a-hilaly** [comment]
A PR is open to fix this bug https://github.com/eksctl-io/eksctl/pull/7480 - we'll ship this in 0.168.0. Stay tuned :)

**Comment by cabeaulac** [comment]
Update on PR and release? My EKS Fargate dev is entirely stopped

**Comment by a-hilaly** [comment]
Trying to do it as soon as possible. We're currently working on fixing some integration tests blocking the release pipeline - will keep you updated in this thread.

**Comment by pschwartz** [comment]
@a-hilaly Are there any updates on this, my teams processes for CI uses this heavily and is currently blocked. Depending on when you feel it can be out, will determine if I have to temporarily build the binary post the PR merge till a release is ready.

**Comment by Spongman** [comment]
can we get a release with this fix?

**Comment by Spongman** [comment]
0.167.0 is the current, broken version

**Comment by Spongman** [comment]
if it were me, i would cherry-pick that change onto the current release and make a 0.167.1. and then i would only need to test that one change, not everythine else that's changed since 0.167.0. :shrug:

**Comment by Spongman** [comment]
yeah, master branch is broken. it can't delete clusters:

```
$ eksctl delete cluster --region=us-east-1 --name=test1
2024-01-18 14:14:54 [ℹ]  deleting EKS cluster "test1"
2024-01-18 14:14:55 [ℹ]  deleted 0 Fargate profile(s)
2024-01-18 14:14:56 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: cannot list Kubernetes Services: Unauthorized
```

whereas 0.167.0 can:
```
$ ./eksctl delete cluster --region=us-east-1 --name=test1
2024-01-18 14:16:25 [ℹ]  deleting EKS cluster "test1"
2024-01-18 14:16:26 [ℹ]  deleted 0 Fargate profile(s)
2024-01-18 14:16:31 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
2024-01-18 14:16:34 [ℹ]  1 task: { delete cluster control plane "test1" [async] }
2024-01-18 14:16:34 [ℹ]  will delete stack "eksctl-test1-cluster"
2024-01-18 14:16:35 [✔]  all cluster resources were deleted
```

**Comment by Spongman** [comment]
ok, i can verify that 0.167.0 with #7480 cherry-picked onto it fixes this issue, _and_ is able to delete clusters.

**Comment by a-hilaly** [comment]
We're preparing `0.168.0` release: https://github.com/eksctl-io/eksctl/pull/7488

**Comment by a-hilaly** [comment]
@Spongman I agree that cherry picking the change would have worked. However while working on it we found out that there another issue (that was very tricky to debug) was blocking the testing/release pipeline wanted to solved with this release as well: https://github.com/eksctl-io/eksctl/pull/7487

**Comment by pschwartz** [comment]
@a-hilaly I think there is another issue. I also cherry-picked it to test and we are getting weird cluster create failures that end in a weird result of `error creating Clientset: getting list of API resources for raw REST client: Unauthorized` and it happens consistently from the v0.167.0 with the PR cherry-picked in.

**Comment by a-hilaly** [comment]
@pschwartz That's exactly what https://github.com/eksctl-io/eksctl/pull/7487 is intended to resolve :)

**Comment by a-hilaly** [comment]
First release candidates for `0.168.0` is out... we're testing it out before shipping the final release.

**Comment by a-hilaly** [comment]
`0.168.0-rc0` binaries are released: https://github.com/eksctl-io/eksctl/releases/tag/v0.168.0-rc.0

**Comment by a-hilaly** [comment]
`0.168.0` binaries are released https://github.com/eksctl-io/eksctl/releases/tag/v0.168.0

**Comment by a-hilaly** [comment]
We'll keep this issue open for one more week to hear your feedback! please test it out and report any malfunction or issues you experience with it. Thank you.

**Comment by molitona** [comment]
@a-hilaly 

why coredns 2 pods are stuck in Pending status?

I created fargate cluster manually with console then with this tool. in both coredns pods stuck in Pending status, what's the problem?
