### ISSUE TITLE
[Bug] `make build` results in "counterfeiter": executable file not found

### ISSUE THREAD

**Issue by Spongman** [eksctl-io/eksctl#7484]
```
git clone ...
make install-build-deps
make build
...
go: downloading github.com/atotto/clipboard v0.1.4
pkg/eks/api.go:59: running "counterfeiter": exec: "counterfeiter": executable file not found in $PATH
make: *** [Makefile:149: generate-always] Error 1
```

Ubuntu 22.04.3 LTS
go-1.20

i'm trying to build myself because the released version is useless (#7479).

**Comment by a-hilaly** [comment]
@Spongman you can build the binary using the Go compiler only: `go build -o eksctl ./cmd/eksctl/*.go`

**Comment by Spongman** [comment]
I was following the instructions in CONTRIBUTING.md. are those broken?

**Comment by yuxiang-zhang** [comment]
Hi @Spongman will you please try the following command before you run `make build`?
```sh
export PATH=$PATH:$(go env GOPATH)/bin
```
