### ISSUE TITLE
[Bug] Deleting EFS Addon Removes CSIDriver Resource

### ISSUE THREAD

**Issue by CrisNevares** [eksctl-io/eksctl#7518]
### What were you trying to accomplish?

Add, then remove the `aws-efs-csi-driver` addon in a Fargate-only cluster.

Because the `efs.csi.aws.com` CSIDriver resource existed prior to the creation of the `aws-efs-csi-driver` addon, I would expect that CSIDriver resource to persist in the cluster if the `aws-efs-csi-driver` is added and subsequently removed.
### What happened?

The `efs.csi.aws.com` CSIDriver resource was deleted
### How to reproduce it?

Create a Fargate-only cluster.
Check that the `efs.csi.aws.com` CSIDriver already exists.
Create the `aws-efs-csi-driver` addon.
Delete the `aws-efs-csi-driver` addon.
Notice the `efs.csi.aws.com` CSIDriver has been deleted.

**Logs**

### Create an eks-test1 cluster, in order to check default csi drivers:
---
```
$ cat eks-test1.yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-test1
  region: us-east-1
  version: "1.27"
  tags:
    environment: dev

kubernetesNetworkConfig:
  ipFamily: IPv4

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
  - name: fp-kube
    selectors:
      - namespace: kube-system


$ eksctl create cluster -f eks-test1.yml
```

### Check csidriver:
---
```
$ kubectl get csidriver
NAME              ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
efs.csi.aws.com   false            false            false             <unset>         false               Persistent   34m

$ kubectl get csidriver -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","metadata":{"annotations":{},"name":"efs.csi.aws.com"},"spec":{"attachRequired":false}}
    creationTimestamp: "2024-01-27T09:30:56Z"
    name: efs.csi.aws.com
    resourceVersion: "272"
    uid: 534abd7e-55c2-45d6-94e9-40b80f5b26df
  spec:
    attachRequired: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: false
    requiresRepublish: false
    storageCapacity: false
    volumeLifecycleModes:
    - Persistent
kind: List
metadata:
  resourceVersion: ""
```

### Install aws-efs-csi-driver addon adding this to eks-test1.yml:
---
```
addons:
  - name: aws-efs-csi-driver
    resolveConflicts: overwrite
```
```
$ eksctl create addon -f eks-test1.yml
```

### I now have efs-csi-controller pods stuck in pending, due to node requirement.  But also note the efs csi driver remains intact:
---
```
$ kubectl get csidriver
NAME              ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
efs.csi.aws.com   false            false            false             <unset>         false               Persistent   38m

$ kubectl get csidriver -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","metadata":{"annotations":{},"name":"efs.csi.aws.com"},"spec":{"attachRequired":false}}
    creationTimestamp: "2024-01-27T09:30:56Z"
    name: efs.csi.aws.com
    resourceVersion: "6373"
    uid: 534abd7e-55c2-45d6-94e9-40b80f5b26df
  spec:
    attachRequired: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: false
    requiresRepublish: false
    storageCapacity: false
    volumeLifecycleModes:
    - Persistent
kind: List
metadata:
  resourceVersion: ""
```

### I now remove the addon:
---
```
$ eksctl delete addon --name aws-efs-csi-driver --cluster eks-test1
```
### Removes the csidriver, not unexpectedly in retrospect:
---
```
$ kubectl get csidriver
No resources found
```
**Anything else we need to know?**

**Versions**

```
$ eksctl info
eksctl version: 0.167.0
kubectl version: v1.28.2
OS: linux
```

**Comment by CrisNevares** [comment]
Bump. This is still an issue.

**Comment by CrisNevares** [comment]
> Hi @CrisNevares , you just need to use the `--preserve` flag for the delete command, this way you'll delete the addon, but preserve the underlying K8s resources.
> 
> ```
> $ eksctl delete addon --name aws-efs-csi-driver --cluster eks-test1 --preserve
> ```
> 
> I'll make a small amendment to the docs so this functionality is explained there as-well.

I don't see why we would need to include the `--preserve` flag for this particular scenario. The `efs.csi.aws.com` CSIDriver object exists prior to installing the addon. So I guess the question is why does `delete addon` remove a resource that it didn't necessarily create?

**Comment by gitcblinn** [comment]
Hello,

I support @CrisNevares here in the need for a better solution. I'm not sure how exactly this would look, but I would definitely be open to following up somewhere else if that makes more sense.

The user experience that I think @CrisNevares ran into and what I just spent the last two days troubleshooting is the following:
1. I tried to set up EKS Fargate cluster for the first time.
2. The EFS CSI Driver documentation is horrific and scattered. I tried installing the EFS CSI Driver in Fargate, but found that this was not allowed to be installed in Fargate when inspecting the erroring pods.
3. Reading more of the documentation, I realized the EFS CSI should already be installed in Fargate. I then troubleshot "driver name efs.csi.aws.com not found in the list of registered CSI drivers" and "timed out waiting for external-attacher of efs.csi.aws.com CSI driver to attach volume" errors while the [aws-efs-csi-driver static provisioning examples](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/static_provisioning) in Git gave me out of date specs to test with.
4. I stumbled upon this bug request, which made me realize that I must have deleted the CSIDriver distributed with the Fargate cluster.

For those looking for a solution, I did the following:
1. Installed the EFS CSI Driver addon again.
2. Ran the "eksctl delete addon --name aws-efs-csi-driver --cluster <cluster_name> --preserve" command.
3. Deleted the unnecessary csi driver daemon with "kubectl delete deployment efs-csi-controller -n kube-system" (though I may be missing some things).
4. Used the following to deploy my PVC:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-test
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <EFS_ID>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
```
I also made sure to add permissions in my EFS security group to allow inbound requests on the NFS port from the Cluster security group of the EKS cluster.

Sure, I think some of this was from my ignorance--I should have read the documentation more carefully. However, to prevent users from completely giving up on this I think it would be helpful to provide some kind of warning that you may be deleting existing resources from the cluster. Would this work better as a feature request?

Thank you!

**Comment by sudhirjena** [comment]
I support the incorrect user/developer experience as observed by @CrisNevares. 

- If AWS recommendation according to [Step 2: Get the Amazon EFS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-install-driver) is to install EFS CSI Driver, EKS cluster created through eksctl should be clean of `efs.csi.aws.com` csidriver.
- If default EKS cluster creation should through eksctl automatically installs `efs.csi.aws.com` csidriver, then it should be fully functioning CSI driver, which it is not unless installed as an Addon.
