### ISSUE TITLE
[Bug] 0.171.0 Typo in STS URL for authentication

### ISSUE THREAD

**Issue by wjpatton** [eksctl-io/eksctl#7549]
### What happened?

Fresh install of eksctl 0.171.0 via Brew on Apple M3.  Attempt "eksctl create cluster" and get an error response with a typo in the STS URL for authentication that contains a double period in the URL.  https://sts..amazonaws

% eksctl create cluster
Error: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://**sts..amazonaws**.com/": dial tcp: lookup sts..amazonaws.com: no such host

### How to reproduce it?

Attempt to use "eksctl create cluster" with 0.171.0

**Logs**

Attempted debug, received no additional output:

Error: checking AWS STS access – cannot get role ARN for current session: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts..amazonaws.com/": dial tcp: lookup sts..amazonaws.com: no such host

**Anything else we need to know?**

What OS are you using?
Brew install of 0.171.0 on M3 Mac with AWS credentials file auth.

**Versions**

% eksctl info
eksctl version: 0.171.0
kubectl version: v1.29.1
OS: darwin

**Comment by yuxiang-zhang** [comment]
Hi @wjpatton this should be fixed via https://github.com/eksctl-io/eksctl/pull/7523
