### ISSUE TITLE
eksctl command not found after install

### ISSUE THREAD

**Issue by Emkloud** [eksctl-io/eksctl#7620]
eksctl : The term 'eksctl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ eksctl version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (eksctl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ibnjunaid** [comment]
Can you share the installation steps you have taken, because it appears that eksctl binary is not in your system's PATH

For windows installation. Kindly refer to this document.

https://eksctl.io/installation/#for-windows
