### ISSUE TITLE
[Bug] Config file partly ignored if redundant whitechars present

### ISSUE THREAD

**Issue by volphy** [eksctl-io/eksctl#7625]
### What were you trying to accomplish?
I wanted to create a new AWS EKS cluster that is compatible with Kubernetes 1.29.

### What happened?
A new cluster compatible with Kubernetes 1.27 was created. A little investigation lead to the conclusion that likely redundant white spaces in the empty line between `version` and `vpc` were to blame.

It would be great if eksctl tool had either separate validation mode (a la `aws cloudformation validate-template ...`) or performed YAML validation at each run.

### How to reproduce it?
```cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-test
  region: eu-west-1
  version: "1.29"
    
vpc:
  id: "vpc-id"
  subnets:
    private:
      eu-west-1a:
        id: "subnet-1a"
      eu-west-1b:
        id: "subnet-1b"
      eu-west-1c:
        id: "subnet-1c"

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP

addons:
  - name: eks-pod-identity-agent
    version: v1.0.0-eksbuild.1

managedNodeGroups:
  - name: ng-1
    labels: { role: workers }
    instanceType: t3a.medium
    desiredCapacity: 1
    volumeSize: 100
    privateNetworking: true
```
_Real identifiers redacted to pseudo-values._

```shell
$ eksctl create cluster -f cluster.yaml
```

**Anything else we need to know?**
My environment:
- OS: MacOS Sonoma 14.3.1
- eksctl binary managed by HomeBrew
- AWS credentials: short-term (environment variables) 

**Versions**
```
$ eksctl info
eksctl version: 0.172.0-dev+15a9f6e37.2024-02-22T21:56:06Z
kubectl version: v1.29.1
OS: darwin
```

**Comment by yuxiang-zhang** [comment]
Hi @volphy, I'm not sure I understand what is the ask here. We have a dry run option that allows you to verify the config before using it: https://eksctl.io/usage/dry-run

**Comment by volphy** [comment]
Thanks.

Dryrun option should be fine for my use case.
