### ISSUE TITLE
[Bug] Update Bottlerocket nodes to latest AMI 1.29

### ISSUE THREAD

**Issue by BogdanRS** [eksctl-io/eksctl#7627]
I am trying to upgrade my manged node-groups with ( eksctl version v0.172):

`eksctl upgrade nodegroup --name=mo-2vcpu-16gb-spot-v2 --kubernetes-version 1.29 --cluster=my-cluster`

I am expecting for the nodes to be upgraded with the latest AMI version on kubernetes version 1.29, but they get reverted to 1.27.

```
eksctl get nodegroup --cluster=my-cluster --region eu-west-1 -o yaml 

- AutoScalingGroupName: eks-mo-2vcpu-16gb-spot-v2-9ac30932-e47d-4be4-aaab-052df2e57413
  Cluster: my-cluster
  CreationTime: "2023-02-02T13:51:48.277Z"
  DesiredCapacity: 2
  ImageID: BOTTLEROCKET_x86_64
  InstanceType: r5n.large,r5b.large,r5a.large
  MaxSize: 5
  MinSize: 2
  Name: mo-2vcpu-16gb-spot-v2
  NodeInstanceRoleARN: <>
  StackName: <>
  Status: ACTIVE
  Type: managed
  Version: "1.27"
```
I have also experienced it when i have upgraded the nodes to version 1.28, i thought it was a bug that would eventually get fixed, so i have upgraded manually from the AWS EKS console.

**Comment by BogdanRS** [comment]
Any updates on this?

**Comment by yuxiang-zhang** [comment]
Hey @BogdanRS could you please share the cluster config you are using?

**Comment by BogdanRS** [comment]
If this helps, sure, but i don't see why is this relevant, I am not using the cluster config to upgrade my clusters.
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: my-cluster
    region: eu-west-1
    version: "1.29"
vpc:
    id: "vpc-0b9bcee0db46d2c98"
    subnets:
      public:
        eu-west-1a:
            id: "subnet-051c76b1a16c67146"
        eu-west-1b:
            id: "subnet-05c1250012070ed33"
      private:
        eu-west-1a:
            id: "subnet-02c30c222646cd766"
        eu-west-1b:
            id: "subnet-0c1c3b7d1f9a04de8"
    clusterEndpoints:
      publicAccess: true
      privateAccess: true
    publicAccessCIDRs: ["x.x.x.x/32"]
iam:
  withOIDC: true  #enables the IAM OIDC provider as well as IRSA for the Amazon CNI plugin
managedNodeGroups:
    - name: gp-2vcpu-8gb-ondemand-v2
      amiFamily: Bottlerocket
      minSize: 2
      maxSize: 3
      desiredCapacity: 2
      volumeSize: 50
      volumeType: gp3
      volumeEncrypted: true
      ssh:
        allow: false
      instanceTypes: ["m6a.large", "m6i.large", "m5a.large"]
      labels:
        lifecycle: OnDemand
      privateNetworking: true
    - name: mo-2vcpu-16gb-spot-v2
      amiFamily: Bottlerocket
      minSize: 2
      maxSize: 5
      desiredCapacity: 2
      volumeSize: 50
      volumeType: gp3
      volumeEncrypted: true
      ssh:
        allow: false
      instanceTypes: ["r5n.large", "r5b.large", "r5a.large"]
      spot: true
      labels:
        lifecycle: Ec2Spot
      privateNetworking: true
secretsEncryption:
  # KMS key used for envelope encryption of Kubernetes secrets
  keyARN: arn:aws:kms:eu-west-1:xxxxx
cloudWatch:
      clusterLogging:
        enableTypes: ["*"]
`

**Comment by yuxiang-zhang** [comment]
Indeed it seems that upgrading Bottlerocket nodes doesn't work currently. I'm able to reproduce the issue and it's not only happening to a specific configuration. 

The support to upgrade Bottlerocket nodes seems to be added recently via https://github.com/eksctl-io/eksctl/issues/6766, but it is still unclear to me how Bottlerocket upgrades are different from AL2 nodes.

**Comment by yuxiang-zhang** [comment]
Upgrade fails because the changeset only contains the following changes
```
[
  {
    "type": "Resource",
    "resourceChange": {
      "action": "Modify",
      "logicalResourceId": "ManagedNodeGroup",
      "physicalResourceId": "bot/ng1",
      "resourceType": "AWS::EKS::Nodegroup",
      "replacement": "False",
      "scope": [
        "Properties"
      ],
      "details": [
        {
          "target": {
            "attribute": "Properties",
            "name": "ForceUpdateEnabled",
            "requiresRecreation": "Never"
          },
          "evaluation": "Static",
          "changeSource": "DirectModification"
        }
      ]
    }
  }
]
```
and as I removed the changes in https://github.com/eksctl-io/eksctl/pull/6923, the changeset became with an explicit `Version` update
```
[
  {
    "type": "Resource",
    "resourceChange": {
      "action": "Modify",
      "logicalResourceId": "LaunchTemplate",
      "physicalResourceId": "lt-0ecfcc25205374c47",
      "resourceType": "AWS::EC2::LaunchTemplate",
      "replacement": "False",
      "scope": [
        "Tags"
      ],
      "details": [
        {
          "target": {
            "attribute": "Tags",
            "requiresRecreation": "Never"
          },
          "evaluation": "Static"
        }
      ]
    }
  },
  {
    "type": "Resource",
    "resourceChange": {
      "action": "Modify",
      "logicalResourceId": "ManagedNodeGroup",
      "physicalResourceId": "bot/ng1",
      "resourceType": "AWS::EKS::Nodegroup",
      "replacement": "Conditional",
      "scope": [
        "Properties",
        "Tags"
      ],
      "details": [
        {
          "target": {
            "attribute": "Tags",
            "requiresRecreation": "Never"
          },
          "evaluation": "Static"
        },
        {
          "target": {
            "attribute": "Properties",
            "name": "NodeRole",
            "requiresRecreation": "Always"
          },
          "evaluation": "Dynamic",
          "changeSource": "ResourceAttribute",
          "causingEntity": "NodeInstanceRole.Arn"
        },
        {
          "target": {
            "attribute": "Properties",
            "name": "Version",
            "requiresRecreation": "Never"
          },
          "evaluation": "Static",
          "changeSource": "DirectModification"
        }
      ]
    }
  },
  {
    "type": "Resource",
    "resourceChange": {
      "action": "Modify",
      "logicalResourceId": "NodeInstanceRole",
      "physicalResourceId": "eksctl-bot-nodegroup-ng1-NodeInstanceRole-UMmA5MFdPHqe",
      "resourceType": "AWS::IAM::Role",
      "replacement": "False",
      "scope": [
        "Tags"
      ],
      "details": [
        {
          "target": {
            "attribute": "Tags",
            "requiresRecreation": "Never"
          },
          "evaluation": "Static"
        }
      ]
    }
  }
]
```
which seems to be exactly what https://github.com/eksctl-io/eksctl/issues/4423 was describing.

**Comment by yuxiang-zhang** [comment]
I compared the new CFN template in the changeset against the old CFN template -- there is no change except the `ManagedNodeGroup.Version` field, yet the changeset still list all of the following as *Changes*: 
- LaunchTemplate
  - Tags
- ManagedNodeGroup
  - Tags
  - NodeRole
  - Version
- NodeInstanceRole
  - Tags

**Comment by BogdanRS** [comment]
Thank you, @yuxiang-zhang, so as i understand there should also be some changes to be made on the bottlerocket side, right? Is it possible for you guys to talk with them about this?

**Comment by yuxiang-zhang** [comment]
@BogdanRS Opened a PR, I tested it myself and it works for me. Would you mind doing a review and test if the fix works for you?

**Comment by BogdanRS** [comment]
Is it ok if you make a patch release with this one? We have a bit of an automated process that only uses eksctl binary from releases.

**Comment by BogdanRS** [comment]
@yuxiang-zhang it doesn't seem to work for me, i have the latest version of eksctl 0.175 and when I upgrade my nodegroups, they still get reverted to eks 1.27...

**Comment by yuxiang-zhang** [comment]
is your cluster on 1.29? how did you upgrade your cluster?

**Comment by yuxiang-zhang** [comment]
I couldn't reproduce what you have. I created a 1.27 cluster, upgraded to 1.29, and then upgraded the nodegroup from 1.27 to 1.29. 

I think to mitigate the issue you are seeing, you could just manually create a changeset that changes the Version to `1.29`.

**Comment by BogdanRS** [comment]
Well, i see it is the same command, the one that i used in the initial post, but for some reason for me it doesn't work and still has the same behavior. Maybe its the fact that the last version that the nodegroups have been created/upgraded with a version of eksctl that didn't contained your changes(the ones in 0.175)? For example, i have this version on the clusters that haven't been upgraded yet, alpha.eksctl.io/eksctl-version - 0.151.0(CF stack).

You could also try, for a test, to create some cluster with that version of eksctl, then upgrade eksctl, then upgrade the nodes. That's the only thing that comes to mind.

**Comment by BogdanRS** [comment]
The Version field was stuck on 1.27 on the Cloudformation stack. So the solution was either to remove that manually or just recreate the nodegroups from scratch.
