### ISSUE TITLE
[Help] EKS cluster does not have addon after upgraded.

### ISSUE THREAD

**Issue by laiminhtrung1997** [eksctl-io/eksctl#7716]
### What help do you need?

I created an EKS cluster without any addons by executing the command:
```
eksctl create cluster --without-nodegroup -f /tmp/cluster.yml
```
Afterward, I upgraded the EKS cluster by modifying the `/tmp/cluster.yml` file to include a new addon, using the command:
```
eksctl upgrade cluster -f /tmp/cluster.yml --approve
```
Although the EKS cluster was successfully upgraded, the addon I added to the `/tmp/cluster.yml` file did not take effect. I believe the `eksctl upgrade cluster` command only performs the upgrade of the EKS cluster version as intended. Is there a solution available to apply new configurations from the `/tmp/cluster.yml` file to the EKS cluster?

**Comment by fargue** [comment]
When we change the add-ons defined in our cluster.yaml file, we run the following command to apply the changes:

`eksctl  update addon --config-file=/tmp/cluster.yaml`

**Comment by cPu1** [comment]
> I believe the eksctl upgrade cluster command only performs the upgrade of the EKS cluster version as intended.

That's correct. `eksctl upgrade cluster` only upgrades the control plane version, it does not look at any other changed fields. 

> Is there a common command to update all configurations in the cluster.yml file to the new EKS cluster?

There's no single command to update the entire configuration. You can find more details at https://eksctl.io.

**Comment by laiminhtrung1997** [comment]
Dear,

I used the `eksctl create addon` command to create an addon after upgrading the EKS cluster from v1.26 to v1.28. The addon was created on EKS, but it has been stuck in the `Creating` state for more than 30 minutes, possibly indefinitely, and the following error message occurred:

```
Error: timed out waiting for addon "aws-guardduty-agent" to become active, status: "CREATING"
```

Has anyone faced this issue? What should I do to resolve it?
