### ISSUE TITLE
[Bug] AL2023 self-managed nodegroups should support `kubeletExtraConfig`

### ISSUE THREAD

**Issue by TiberiuGC** [eksctl-io/eksctl#7751]
Currently, there's a validation in place that prevents the use case described in the title, e.g.

`Error: could not create cluster provider from options: kubeletExtraConfig is not supported for AmazonLinux2023 nodegroups (path=nodeGroups[0].kubeletExtraConfig)`

For self-managed AL2023 nodes, we need to build the kubelet config file and pass it to the nodeadm process via `nodeConfig.kubelet.flags` i.e. `--config`.

**Comment by punkwalker** [comment]
@TiberiuGC 
The nodeadm does not allow passing just kubelet config via file,
It has to be the entire NodeConfig and it has to be passed as `nodeadm config --config-source`.
However, doing so would require executing nodeadm via user data.

EKS Optimized AMIs have Service Unit files for nodeadm `/etc/systemd/system/nodeadm-config.service & /etc/systemd/system/nodeadm-run.service` and it utilizes user data as source for `NodeConfig`.

Therefore, we should be building `NodeConfig` in UserData

**Comment by punkwalker** [comment]
@TiberiuGC 
I see, I think this should work. I will try to test it.

**Comment by punkwalker** [comment]
Sure @TiberiuGC I will work on it.
