### ISSUE TITLE
[Help]  What is the right way to upgrade a nodegroup with different launch template version?

### ISSUE THREAD

**Issue by ok512** [eksctl-io/eksctl#7786]
eksctl version: **0.179.0**

I'm trying to follow [doc](https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html)
_Note:
If you're upgrading a node group that's deployed with a launch template to a new launch template version, add --launch-template-version version-number to the preceding command._

All these commands:
```
eksctl upgrade nodegroup --kubernetes-version 1.30 --profile tnet-dev --cluster test --name ng1
eksctl upgrade nodegroup --kubernetes-version 1.30 --profile tnet-dev --cluster test --name ng1 --launch-template-version 4
eksctl upgrade nodegroup --launch-template-version 4 --kubernetes-version 1.30 --profile tnet-dev --cluster test --name ng1
```
show error:
_[ℹ]  waiting for CloudFormation stack "eksctl-test-nodegroup-ng1"
Error: error fetching launch template data: operation error EC2: DescribeLaunchTemplateVersions, 
https response error StatusCode: 400, RequestID: 98c3e445-3160-45e7-8c28-a469a875c5d2, 
api error InvalidLaunchTemplateId.VersionNotFound: 
Could not find the specified version 1 for the launch template with ID lt-0f3e2efa769a315f6._

Why and what for eksctl wants version **1** of launch template?
The nodegroup uses version **4** and it's default and latest launch template version too.

Am I missing something? 😕

**Comment by cPu1** [comment]
@ok512, did you happen to delete the version of the launch template the nodegroup was originally created with? Can you post the output of the following command, redacting any sensitive information?

```shell
$ aws ec2 describe-launch-template-versions --launch-template-id lt-0f3e2efa769a315f6
```

**Comment by ok512** [comment]
> did you happen to delete the version of the launch template the nodegroup was originally created with? Can you post the output of the following command, redacting any sensitive information?

Yes, because it's not used anywhere.
Why would it be a problem for `eksctl`?
