### ISSUE TITLE
[Feedback] Nodegroups - /usage/nodegroups/

### ISSUE THREAD

**Issue by ok512** [eksctl-io/eksctl#7787]
"eksctl upgrade" is missing...?

**Comment by cPu1** [comment]
`eksctl upgrade nodegroup` is under [https://eksctl.io/usage/nodegroup-managed/?h=node#upgrading-managed-nodegroups](EKS managed nodegroups). It's because that command is not supported for self-managed nodegroups.

**Comment by cPu1** [comment]
`eksctl upgrade nodegroup` is under [EKS managed nodegroups](https://eksctl.io/usage/nodegroup-managed/?h=node#upgrading-managed-nodegroups). It's because that command is not supported for self-managed nodegroups.
