### ISSUE TITLE
[Bug] a non-GPU AMI is used for g6 instance types 

### ISSUE THREAD

**Issue by ebr** [eksctl-io/eksctl#7794]
### What were you trying to accomplish?

Attempted to create a self-managed GPU-enabled nodegroup using a `g6.xlarge` instance. 

### What happened?

The autoscaling group / launch config was created using the [ami-0bf80365cb35eb783](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-0bf80365cb35eb783) AMI , which is the standard EKS-optimized AMI. 

The expectation is that [ami-04d839ff8959772fc](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-04d839ff8959772fc) AMI would be used.

### How to reproduce it?

```
---
nodeGroups:
  - name: gpu-ng
    instanceType: g6.xlarge
---

```

**Versions**

```
$ eksctl info
eksctl version: 0.179.0
kubectl version: v1.30.0
OS: linux
```

**Comment by practicusai** [comment]
https://github.com/eksctl-io/eksctl/pull/7819

**Comment by ebr** [comment]
Thank you for the prompt fix!
