### ISSUE TITLE
[Help] Cant install eksctl on macOS Monterey

### ISSUE THREAD

**Issue by justmic007** [eksctl-io/eksctl#7873]
Please help, i cannot install eksctl on macOS Monterey. My system architecture is x86_64

I have tried installing using Homebrew

1. I ran the following commands:
      
```
          brew tap weaveworks/tap
          brew install weaveworks/tap/eksctl -v
```
      

but got the error log message below:

<details>
micah@Micahs-MBP Downloads % brew install weaveworks/tap/eksctl -v
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching dependencies for weaveworks/tap/eksctl: aws-iam-authenticator and kubernetes-cli
==> Fetching aws-iam-authenticator
==> Downloading https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/manifests/0.6.21
Already downloaded: /Users/micah/Library/Caches/Homebrew/downloads/c288deba9bf81d7103d5c67494244168cec4979e8d4cc017fdbb4cd2d7a5846c--aws-iam-authenticator-0.6.21.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:6d57c0f3c2a16a0267f9cd3eab3073c778e06178a1f6a75ba83cd9b85d2aed0e
Already downloaded: /Users/micah/Library/Caches/Homebrew/downloads/92c1e29e39dc9f6d75101fdaeb3a898560609cd5b025afa302207f788a754e06--aws-iam-authenticator--0.6.21.monterey.bottle.tar.gz
==> Verifying checksum for '92c1e29e39dc9f6d75101fdaeb3a898560609cd5b025afa302207f788a754e06--aws-iam-authenticator--0.6.21.monterey.bottle.tar.gz'
==> Fetching kubernetes-cli
==> Downloading https://ghcr.io/v2/homebrew/core/kubernetes-cli/manifests/1.30.2
Already downloaded: /Users/micah/Library/Caches/Homebrew/downloads/6dbab7e19b3ac6353f5e603129db0742f12ac4670ef441cec9c8387438477990--kubernetes-cli-1.30.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/kubernetes-cli/blobs/sha256:39856bb14b195c990ba84f1c7b4ca1a603d03f5ac3eec119a8043b42224bad39
Already downloaded: /Users/micah/Library/Caches/Homebrew/downloads/f148b0a772629680af7488cfb32cc674922e32c49033b5062a92deb3c74377ff--kubernetes-cli--1.30.2.monterey.bottle.tar.gz
==> Verifying checksum for 'f148b0a772629680af7488cfb32cc674922e32c49033b5062a92deb3c74377ff--kubernetes-cli--1.30.2.monterey.bottle.tar.gz'
==> Fetching weaveworks/tap/eksctl
==> Downloading https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.7.5\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/micah/Library/Caches/Homebrew/downloads/1eb7208ef22d35941e33054935d8d97d694cde041742a464e776eb915d4f5107--eksctl_Darwin_amd64.tar.gz.incomplete --location https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:03:54 --:--:--     0
curl: (35) Recv failure: Operation timed out
Error: eksctl: Failed to download resource "eksctl"
Download failed: https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz
micah@Micahs-MBP Downloads %
</details>

2. I have also tried downloading using curl command:
 
```
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz" -v
```

but failed. I got the error logs below:

<details>            
            *   Trying 140.82.121.3:443...
            * Connected to github.com (140.82.121.3) port 443
            * ALPN: curl offers h2,http/1.1
            * (304) (OUT), TLS handshake, Client hello (1):
            } [315 bytes data]
            *  CAfile: /etc/ssl/cert.pem
            *  CApath: none
            * (304) (IN), TLS handshake, Server hello (2):
            { [122 bytes data]
            * (304) (IN), TLS handshake, Unknown (8):
            { [19 bytes data]
            * (304) (IN), TLS handshake, Certificate (11):
            { [3137 bytes data]
            * (304) (IN), TLS handshake, CERT verify (15):
            { [79 bytes data]
            * (304) (IN), TLS handshake, Finished (20):
            { [36 bytes data]
            * (304) (OUT), TLS handshake, Finished (20):
            } [36 bytes data]
            * SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
            * ALPN: server accepted h2
            * Server certificate:
            *  subject: CN=github.com
            *  start date: Mar  7 00:00:00 2024 GMT
            *  expire date: Mar  7 23:59:59 2025 GMT
            *  subjectAltName: host "github.com" matched cert's "github.com"
            *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo ECC Domain Validation Secure Server CA
            *  SSL certificate verify ok.
            * using HTTP/2
            * [HTTP/2] [1] OPENED stream for https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Darwin_amd64.tar.gz
            * [HTTP/2] [1] [:method: GET]
            * [HTTP/2] [1] [:scheme: https]
            * [HTTP/2] [1] [:authority: github.com]
            * [HTTP/2] [1] [:path: /eksctl-io/eksctl/releases/latest/download/eksctl_Darwin_amd64.tar.gz]
            * [HTTP/2] [1] [user-agent: curl/8.4.0]
            * [HTTP/2] [1] [accept: */*]
            > GET /eksctl-io/eksctl/releases/latest/download/eksctl_Darwin_amd64.tar.gz HTTP/2
            > Host: github.com
            > User-Agent: curl/8.4.0
            > Accept: */*
            >
            < HTTP/2 302
            < server: GitHub.com
            < date: Sun, 07 Jul 2024 20:05:20 GMT
            < content-type: text/html; charset=utf-8
            < vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
            < location: https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz
            < cache-control: no-cache
            < strict-transport-security: max-age=31536000; includeSubdomains; preload
            < x-frame-options: deny
            < x-content-type-options: nosniff
            < x-xss-protection: 0
            < referrer-policy: no-referrer-when-downgrade
            < content-security-policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com api.githubcopilot.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com/v1/engines/github-completion/completions *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
            < set-cookie: _gh_sess=w838TsBNYmxmU6DWvNacnyN274sHiBsaEwW9iM28Bdw4WZDYKFXMIqgN%2BoJ%2FMr%2Fqo5iKSLJN0spDLU70GBXvpUmGi3xmtMdl6DL089bGqPYb%2FkMYmEi%2FqbRBgvn5JHRFl%2F9Y6OLa4XqcO31qLqUWPXh64%2BwRkeNMBmUtH8InSdKnXQuYJcyjzuQ0zgSyV8WUTmbWE0S1%2Ft%2FzKiBduMJ9IAa34IixgrUmZIS8Q%2BYzydFwhjThtS1klGkwRgo6tERc%2FrRZzupUhAb0GSxhxNmknQ%3D%3D--HKZJhlngjz23dX6p--9dC04HJ4l0MFnnH%2FFELYYQ%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
            < set-cookie: _octo=GH1.1.2123168106.1720382720; Path=/; Domain=github.com; Expires=Mon, 07 Jul 2025 20:05:20 GMT; Secure; SameSite=Lax
            < set-cookie: logged_in=no; Path=/; Domain=github.com; Expires=Mon, 07 Jul 2025 20:05:20 GMT; HttpOnly; Secure; SameSite=Lax
            < content-length: 0
            < x-github-request-id: 2DCB:16DB51:8C86830:8FEC9CC:668AF4FF
            <
            { [0 bytes data]
            * Connection #0 to host github.com left intact
            * Issue another request to this URL: 'https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz'
            * Found bundle for host: 0x6000009948d0 [can multiplex]
            * Re-using existing connection with host github.com
            * [HTTP/2] [3] OPENED stream for https://github.com/eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz
            * [HTTP/2] [3] [:method: GET]
            * [HTTP/2] [3] [:scheme: https]
            * [HTTP/2] [3] [:authority: github.com]
            * [HTTP/2] [3] [:path: /eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz]
            * [HTTP/2] [3] [user-agent: curl/8.4.0]
            * [HTTP/2] [3] [accept: */*]
            > GET /eksctl-io/eksctl/releases/download/v0.184.0/eksctl_Darwin_amd64.tar.gz HTTP/2
            > Host: github.com
            > User-Agent: curl/8.4.0
            > Accept: */*
            >
            < HTTP/2 302
            < server: GitHub.com
            < date: Sun, 07 Jul 2024 20:05:21 GMT
            < content-type: text/html; charset=utf-8
            < vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
            < location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/134539560/f5ca818b-0b5a-4921-8f22-0059ecf02505?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240707%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240707T200521Z&X-Amz-Expires=300&X-Amz-Signature=44dc2ba46ff0c2b97f46d6d97bd6b68b0a1634f24dcf7f7c4b3ca46be87aee83&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=134539560&response-content-disposition=attachment%3B%20filename%3Deksctl_Darwin_amd64.tar.gz&response-content-type=application%2Foctet-stream
            < cache-control: no-cache
            < strict-transport-security: max-age=31536000; includeSubdomains; preload
            < x-frame-options: deny
            < x-content-type-options: nosniff
            < x-xss-protection: 0
            < referrer-policy: no-referrer-when-downgrade
            < content-security-policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com api.githubcopilot.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com/v1/engines/github-completion/completions *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
            < content-length: 0
            < x-github-request-id: 2DCB:16DB51:8C86A61:8FECBE9:668AF500
            <
            { [0 bytes data]
            * Connection #0 to host github.com left intact
            * Issue another request to this URL: 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/134539560/f5ca818b-0b5a-4921-8f22-0059ecf02505?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240707%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240707T200521Z&X-Amz-Expires=300&X-Amz-Signature=44dc2ba46ff0c2b97f46d6d97bd6b68b0a1634f24dcf7f7c4b3ca46be87aee83&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=134539560&response-content-disposition=attachment%3B%20filename%3Deksctl_Darwin_amd64.tar.gz&response-content-type=application%2Foctet-stream'
            *   Trying 185.199.111.133:443...
            * Connected to objects.githubusercontent.com (185.199.111.133) port 443
            * ALPN: curl offers h2,http/1.1
            * (304) (OUT), TLS handshake, Client hello (1):
            } [334 bytes data]
            * SSL connection timeout
            * Closing connection
            micah@Micahs-MBP Downloads %

</details>

3. I have also tried to download the tar file drirectly using the browser(see screenshot below). When i click on the file i needed to download in the Assets, i still coudn't download it.

<img width="1305" alt="Screenshot 2024-07-07 at 21 09 54" src="https://github.com/eksctl-io/eksctl/assets/36313854/b8e63d1a-099c-4bc3-b776-f0354a4eea16">

I would appreciate any guidance on how to solve this issue. Thank you.

**Comment by mdgm88** [comment]
@justmic007, I think the instructions may need an update.

Perhaps try simply:
brew install eksctl
