### ISSUE TITLE
panic: "" not a valid CLUSTER_ENDPOINT URL; CLUSTER_NAME is required -- Karpenter

### ISSUE THREAD

**Issue by oluranticode** [eksctl-io/eksctl#7926]
I'm getting this error while trying to install karpenter in my kubernetes. see configuration below

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: system
  source:
    repoURL: 'https://charts.karpenter.sh'
    chart: karpenter
    targetRevision: {{ index .Values "targetRevision" "karpenter" }}
    helm:
      values: |
       aws:
          clusterName: ""
          clusterEndpoint: ""
          defaultInstanceProfile: "KarpenterInstanceProfile"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      
      
      Error i'm getting is:
      panic: "" not a valid CLUSTER_ENDPOINT URL; CLUSTER_NAME is required
goroutine 1 [running]:
github.com/aws/karpenter/pkg/utils/options.(*Options).MustParse(0x4000711680)
	github.com/aws/karpenter/pkg/utils/options/options.go:97 +0x110
github.com/aws/karpenter/pkg/controllers.Initialize(0x20cd038)
	github.com/aws/karpenter/pkg/controllers/controllers.go:89 +0x2c
main.main()
	github.com/aws/karpenter/cmd/controller/main.go:26 +0x24
	
	
	please can anyone help me

**Comment by cPu1** [comment]
Did you install Karpenter via eksctl? As the error indicates, you'll need to set a valid `CLUSTER_ENDPOINT_URL` and `CLUSTER_NAME`. This does not seem related to eksctl.

**Comment by ebidrey** [comment]
hi,

did u fix it?
