### ISSUE TITLE
[Help] eksctl does not support configuring maxPodsPerNode EKS-managed nodes based on AmazonLinux2023

### ISSUE THREAD

**Issue by kundkingan** [eksctl-io/eksctl#7928]
Trying to increase number of pods per node, but seems to be blocked by `eksctl`.
We are getting `eksctl does not support configuring maxPodsPerNode EKS-managed nodes based on AmazonLinux2023`. 

How do we increase the max number of pods if its blocked by AmazonLinux2023? 

Currently using `t4g.medium` instance

**Comment by WalBeh** [comment]
@kundkingan are you using `AmazonLinux2023` at all? 

In our case we had been using `AL2` (which is the default) and got the same error message  as yours, with `eksctl` `0.189.0`. After manually adding `amiFamily: AmazonLinux2` to each nodegroups configuration, upgrade worked. 

Hope that helps also on your side, if not, never mind.

**Comment by kundkingan** [comment]
@WalBeh Seems like we hade the wrong version of eksctl loacally...
