### ISSUE TITLE
[Feedback] Config File Schema - /usage/schema/

### ISSUE THREAD

**Issue by DariusX** [eksctl-io/eksctl#7998]
The schema page does not drill down enough. Ideally, it would provide the entire schema down to the last detail, and would also mention default behavior. The Kubernetes API reference is a good example.
Is there a detailed reference like that for  eksctl ?

**Comment by DariusX** [comment]
Thanks @cPu1 
Is there a particular place in the code that a developer could look at, in order to get a definitive picture of what is allowed in a config.yaml file passed to eksctl?

**Comment by cPu1** [comment]
> Thanks @cPu1 Is there a particular place in the code that a developer could look at, in order to get a definitive picture of what is allowed in a config.yaml file passed to eksctl?

Yes. This is good starting point: https://github.com/eksctl-io/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/types.go#L884.

**Comment by cPu1** [comment]
> Thanks @cPu1 Is there a particular place in the code that a developer could look at, in order to get a definitive picture of what is allowed in a config.yaml file passed to eksctl?

Yes. This is a good starting point: https://github.com/eksctl-io/eksctl/blob/main/pkg/apis/eksctl.io/v1alpha5/types.go#L884.
